package com.greenplatform.dao;

import com.greenplatform.model.TGreenGoldHz;
import com.greenplatform.model.TGreenGoldHzExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TGreenGoldHzMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_gold_hz
     *
     * @mbggenerated
     */
    int countByExample(TGreenGoldHzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_gold_hz
     *
     * @mbggenerated
     */
    int deleteByExample(TGreenGoldHzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_gold_hz
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String cUserid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_gold_hz
     *
     * @mbggenerated
     */
    int insert(TGreenGoldHz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_gold_hz
     *
     * @mbggenerated
     */
    int insertSelective(TGreenGoldHz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_gold_hz
     *
     * @mbggenerated
     */
    List<TGreenGoldHz> selectByExample(TGreenGoldHzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_gold_hz
     *
     * @mbggenerated
     */
    TGreenGoldHz selectByPrimaryKey(String cUserid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_gold_hz
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TGreenGoldHz record, @Param("example") TGreenGoldHzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_gold_hz
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TGreenGoldHz record, @Param("example") TGreenGoldHzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_gold_hz
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TGreenGoldHz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_gold_hz
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TGreenGoldHz record);
}