package com.greenplatform.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TGreenSpSpmxExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_green_sp_spmx
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_green_sp_spmx
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_green_sp_spmx
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_sp_spmx
     *
     * @mbggenerated
     */
    public TGreenSpSpmxExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_sp_spmx
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_sp_spmx
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_sp_spmx
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_sp_spmx
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_sp_spmx
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_sp_spmx
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_sp_spmx
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_sp_spmx
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_sp_spmx
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_sp_spmx
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_green_sp_spmx
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCSpbhIsNull() {
            addCriterion("c_spbh is null");
            return (Criteria) this;
        }

        public Criteria andCSpbhIsNotNull() {
            addCriterion("c_spbh is not null");
            return (Criteria) this;
        }

        public Criteria andCSpbhEqualTo(String value) {
            addCriterion("c_spbh =", value, "cSpbh");
            return (Criteria) this;
        }

        public Criteria andCSpbhNotEqualTo(String value) {
            addCriterion("c_spbh <>", value, "cSpbh");
            return (Criteria) this;
        }

        public Criteria andCSpbhGreaterThan(String value) {
            addCriterion("c_spbh >", value, "cSpbh");
            return (Criteria) this;
        }

        public Criteria andCSpbhGreaterThanOrEqualTo(String value) {
            addCriterion("c_spbh >=", value, "cSpbh");
            return (Criteria) this;
        }

        public Criteria andCSpbhLessThan(String value) {
            addCriterion("c_spbh <", value, "cSpbh");
            return (Criteria) this;
        }

        public Criteria andCSpbhLessThanOrEqualTo(String value) {
            addCriterion("c_spbh <=", value, "cSpbh");
            return (Criteria) this;
        }

        public Criteria andCSpbhLike(String value) {
            addCriterion("c_spbh like", value, "cSpbh");
            return (Criteria) this;
        }

        public Criteria andCSpbhNotLike(String value) {
            addCriterion("c_spbh not like", value, "cSpbh");
            return (Criteria) this;
        }

        public Criteria andCSpbhIn(List<String> values) {
            addCriterion("c_spbh in", values, "cSpbh");
            return (Criteria) this;
        }

        public Criteria andCSpbhNotIn(List<String> values) {
            addCriterion("c_spbh not in", values, "cSpbh");
            return (Criteria) this;
        }

        public Criteria andCSpbhBetween(String value1, String value2) {
            addCriterion("c_spbh between", value1, value2, "cSpbh");
            return (Criteria) this;
        }

        public Criteria andCSpbhNotBetween(String value1, String value2) {
            addCriterion("c_spbh not between", value1, value2, "cSpbh");
            return (Criteria) this;
        }

        public Criteria andCSpmcIsNull() {
            addCriterion("c_spmc is null");
            return (Criteria) this;
        }

        public Criteria andCSpmcIsNotNull() {
            addCriterion("c_spmc is not null");
            return (Criteria) this;
        }

        public Criteria andCSpmcEqualTo(String value) {
            addCriterion("c_spmc =", value, "cSpmc");
            return (Criteria) this;
        }

        public Criteria andCSpmcNotEqualTo(String value) {
            addCriterion("c_spmc <>", value, "cSpmc");
            return (Criteria) this;
        }

        public Criteria andCSpmcGreaterThan(String value) {
            addCriterion("c_spmc >", value, "cSpmc");
            return (Criteria) this;
        }

        public Criteria andCSpmcGreaterThanOrEqualTo(String value) {
            addCriterion("c_spmc >=", value, "cSpmc");
            return (Criteria) this;
        }

        public Criteria andCSpmcLessThan(String value) {
            addCriterion("c_spmc <", value, "cSpmc");
            return (Criteria) this;
        }

        public Criteria andCSpmcLessThanOrEqualTo(String value) {
            addCriterion("c_spmc <=", value, "cSpmc");
            return (Criteria) this;
        }

        public Criteria andCSpmcLike(String value) {
            addCriterion("c_spmc like", value, "cSpmc");
            return (Criteria) this;
        }

        public Criteria andCSpmcNotLike(String value) {
            addCriterion("c_spmc not like", value, "cSpmc");
            return (Criteria) this;
        }

        public Criteria andCSpmcIn(List<String> values) {
            addCriterion("c_spmc in", values, "cSpmc");
            return (Criteria) this;
        }

        public Criteria andCSpmcNotIn(List<String> values) {
            addCriterion("c_spmc not in", values, "cSpmc");
            return (Criteria) this;
        }

        public Criteria andCSpmcBetween(String value1, String value2) {
            addCriterion("c_spmc between", value1, value2, "cSpmc");
            return (Criteria) this;
        }

        public Criteria andCSpmcNotBetween(String value1, String value2) {
            addCriterion("c_spmc not between", value1, value2, "cSpmc");
            return (Criteria) this;
        }

        public Criteria andCSpmsIsNull() {
            addCriterion("c_spms is null");
            return (Criteria) this;
        }

        public Criteria andCSpmsIsNotNull() {
            addCriterion("c_spms is not null");
            return (Criteria) this;
        }

        public Criteria andCSpmsEqualTo(String value) {
            addCriterion("c_spms =", value, "cSpms");
            return (Criteria) this;
        }

        public Criteria andCSpmsNotEqualTo(String value) {
            addCriterion("c_spms <>", value, "cSpms");
            return (Criteria) this;
        }

        public Criteria andCSpmsGreaterThan(String value) {
            addCriterion("c_spms >", value, "cSpms");
            return (Criteria) this;
        }

        public Criteria andCSpmsGreaterThanOrEqualTo(String value) {
            addCriterion("c_spms >=", value, "cSpms");
            return (Criteria) this;
        }

        public Criteria andCSpmsLessThan(String value) {
            addCriterion("c_spms <", value, "cSpms");
            return (Criteria) this;
        }

        public Criteria andCSpmsLessThanOrEqualTo(String value) {
            addCriterion("c_spms <=", value, "cSpms");
            return (Criteria) this;
        }

        public Criteria andCSpmsLike(String value) {
            addCriterion("c_spms like", value, "cSpms");
            return (Criteria) this;
        }

        public Criteria andCSpmsNotLike(String value) {
            addCriterion("c_spms not like", value, "cSpms");
            return (Criteria) this;
        }

        public Criteria andCSpmsIn(List<String> values) {
            addCriterion("c_spms in", values, "cSpms");
            return (Criteria) this;
        }

        public Criteria andCSpmsNotIn(List<String> values) {
            addCriterion("c_spms not in", values, "cSpms");
            return (Criteria) this;
        }

        public Criteria andCSpmsBetween(String value1, String value2) {
            addCriterion("c_spms between", value1, value2, "cSpms");
            return (Criteria) this;
        }

        public Criteria andCSpmsNotBetween(String value1, String value2) {
            addCriterion("c_spms not between", value1, value2, "cSpms");
            return (Criteria) this;
        }

        public Criteria andNSpjgIsNull() {
            addCriterion("n_spjg is null");
            return (Criteria) this;
        }

        public Criteria andNSpjgIsNotNull() {
            addCriterion("n_spjg is not null");
            return (Criteria) this;
        }

        public Criteria andNSpjgEqualTo(BigDecimal value) {
            addCriterion("n_spjg =", value, "nSpjg");
            return (Criteria) this;
        }

        public Criteria andNSpjgNotEqualTo(BigDecimal value) {
            addCriterion("n_spjg <>", value, "nSpjg");
            return (Criteria) this;
        }

        public Criteria andNSpjgGreaterThan(BigDecimal value) {
            addCriterion("n_spjg >", value, "nSpjg");
            return (Criteria) this;
        }

        public Criteria andNSpjgGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("n_spjg >=", value, "nSpjg");
            return (Criteria) this;
        }

        public Criteria andNSpjgLessThan(BigDecimal value) {
            addCriterion("n_spjg <", value, "nSpjg");
            return (Criteria) this;
        }

        public Criteria andNSpjgLessThanOrEqualTo(BigDecimal value) {
            addCriterion("n_spjg <=", value, "nSpjg");
            return (Criteria) this;
        }

        public Criteria andNSpjgIn(List<BigDecimal> values) {
            addCriterion("n_spjg in", values, "nSpjg");
            return (Criteria) this;
        }

        public Criteria andNSpjgNotIn(List<BigDecimal> values) {
            addCriterion("n_spjg not in", values, "nSpjg");
            return (Criteria) this;
        }

        public Criteria andNSpjgBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("n_spjg between", value1, value2, "nSpjg");
            return (Criteria) this;
        }

        public Criteria andNSpjgNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("n_spjg not between", value1, value2, "nSpjg");
            return (Criteria) this;
        }

        public Criteria andCSpdwIsNull() {
            addCriterion("c_spdw is null");
            return (Criteria) this;
        }

        public Criteria andCSpdwIsNotNull() {
            addCriterion("c_spdw is not null");
            return (Criteria) this;
        }

        public Criteria andCSpdwEqualTo(String value) {
            addCriterion("c_spdw =", value, "cSpdw");
            return (Criteria) this;
        }

        public Criteria andCSpdwNotEqualTo(String value) {
            addCriterion("c_spdw <>", value, "cSpdw");
            return (Criteria) this;
        }

        public Criteria andCSpdwGreaterThan(String value) {
            addCriterion("c_spdw >", value, "cSpdw");
            return (Criteria) this;
        }

        public Criteria andCSpdwGreaterThanOrEqualTo(String value) {
            addCriterion("c_spdw >=", value, "cSpdw");
            return (Criteria) this;
        }

        public Criteria andCSpdwLessThan(String value) {
            addCriterion("c_spdw <", value, "cSpdw");
            return (Criteria) this;
        }

        public Criteria andCSpdwLessThanOrEqualTo(String value) {
            addCriterion("c_spdw <=", value, "cSpdw");
            return (Criteria) this;
        }

        public Criteria andCSpdwLike(String value) {
            addCriterion("c_spdw like", value, "cSpdw");
            return (Criteria) this;
        }

        public Criteria andCSpdwNotLike(String value) {
            addCriterion("c_spdw not like", value, "cSpdw");
            return (Criteria) this;
        }

        public Criteria andCSpdwIn(List<String> values) {
            addCriterion("c_spdw in", values, "cSpdw");
            return (Criteria) this;
        }

        public Criteria andCSpdwNotIn(List<String> values) {
            addCriterion("c_spdw not in", values, "cSpdw");
            return (Criteria) this;
        }

        public Criteria andCSpdwBetween(String value1, String value2) {
            addCriterion("c_spdw between", value1, value2, "cSpdw");
            return (Criteria) this;
        }

        public Criteria andCSpdwNotBetween(String value1, String value2) {
            addCriterion("c_spdw not between", value1, value2, "cSpdw");
            return (Criteria) this;
        }

        public Criteria andCImgurlIsNull() {
            addCriterion("c_imgurl is null");
            return (Criteria) this;
        }

        public Criteria andCImgurlIsNotNull() {
            addCriterion("c_imgurl is not null");
            return (Criteria) this;
        }

        public Criteria andCImgurlEqualTo(String value) {
            addCriterion("c_imgurl =", value, "cImgurl");
            return (Criteria) this;
        }

        public Criteria andCImgurlNotEqualTo(String value) {
            addCriterion("c_imgurl <>", value, "cImgurl");
            return (Criteria) this;
        }

        public Criteria andCImgurlGreaterThan(String value) {
            addCriterion("c_imgurl >", value, "cImgurl");
            return (Criteria) this;
        }

        public Criteria andCImgurlGreaterThanOrEqualTo(String value) {
            addCriterion("c_imgurl >=", value, "cImgurl");
            return (Criteria) this;
        }

        public Criteria andCImgurlLessThan(String value) {
            addCriterion("c_imgurl <", value, "cImgurl");
            return (Criteria) this;
        }

        public Criteria andCImgurlLessThanOrEqualTo(String value) {
            addCriterion("c_imgurl <=", value, "cImgurl");
            return (Criteria) this;
        }

        public Criteria andCImgurlLike(String value) {
            addCriterion("c_imgurl like", value, "cImgurl");
            return (Criteria) this;
        }

        public Criteria andCImgurlNotLike(String value) {
            addCriterion("c_imgurl not like", value, "cImgurl");
            return (Criteria) this;
        }

        public Criteria andCImgurlIn(List<String> values) {
            addCriterion("c_imgurl in", values, "cImgurl");
            return (Criteria) this;
        }

        public Criteria andCImgurlNotIn(List<String> values) {
            addCriterion("c_imgurl not in", values, "cImgurl");
            return (Criteria) this;
        }

        public Criteria andCImgurlBetween(String value1, String value2) {
            addCriterion("c_imgurl between", value1, value2, "cImgurl");
            return (Criteria) this;
        }

        public Criteria andCImgurlNotBetween(String value1, String value2) {
            addCriterion("c_imgurl not between", value1, value2, "cImgurl");
            return (Criteria) this;
        }

        public Criteria andCBzIsNull() {
            addCriterion("c_bz is null");
            return (Criteria) this;
        }

        public Criteria andCBzIsNotNull() {
            addCriterion("c_bz is not null");
            return (Criteria) this;
        }

        public Criteria andCBzEqualTo(String value) {
            addCriterion("c_bz =", value, "cBz");
            return (Criteria) this;
        }

        public Criteria andCBzNotEqualTo(String value) {
            addCriterion("c_bz <>", value, "cBz");
            return (Criteria) this;
        }

        public Criteria andCBzGreaterThan(String value) {
            addCriterion("c_bz >", value, "cBz");
            return (Criteria) this;
        }

        public Criteria andCBzGreaterThanOrEqualTo(String value) {
            addCriterion("c_bz >=", value, "cBz");
            return (Criteria) this;
        }

        public Criteria andCBzLessThan(String value) {
            addCriterion("c_bz <", value, "cBz");
            return (Criteria) this;
        }

        public Criteria andCBzLessThanOrEqualTo(String value) {
            addCriterion("c_bz <=", value, "cBz");
            return (Criteria) this;
        }

        public Criteria andCBzLike(String value) {
            addCriterion("c_bz like", value, "cBz");
            return (Criteria) this;
        }

        public Criteria andCBzNotLike(String value) {
            addCriterion("c_bz not like", value, "cBz");
            return (Criteria) this;
        }

        public Criteria andCBzIn(List<String> values) {
            addCriterion("c_bz in", values, "cBz");
            return (Criteria) this;
        }

        public Criteria andCBzNotIn(List<String> values) {
            addCriterion("c_bz not in", values, "cBz");
            return (Criteria) this;
        }

        public Criteria andCBzBetween(String value1, String value2) {
            addCriterion("c_bz between", value1, value2, "cBz");
            return (Criteria) this;
        }

        public Criteria andCBzNotBetween(String value1, String value2) {
            addCriterion("c_bz not between", value1, value2, "cBz");
            return (Criteria) this;
        }

        public Criteria andCZtIsNull() {
            addCriterion("c_zt is null");
            return (Criteria) this;
        }

        public Criteria andCZtIsNotNull() {
            addCriterion("c_zt is not null");
            return (Criteria) this;
        }

        public Criteria andCZtEqualTo(String value) {
            addCriterion("c_zt =", value, "cZt");
            return (Criteria) this;
        }

        public Criteria andCZtNotEqualTo(String value) {
            addCriterion("c_zt <>", value, "cZt");
            return (Criteria) this;
        }

        public Criteria andCZtGreaterThan(String value) {
            addCriterion("c_zt >", value, "cZt");
            return (Criteria) this;
        }

        public Criteria andCZtGreaterThanOrEqualTo(String value) {
            addCriterion("c_zt >=", value, "cZt");
            return (Criteria) this;
        }

        public Criteria andCZtLessThan(String value) {
            addCriterion("c_zt <", value, "cZt");
            return (Criteria) this;
        }

        public Criteria andCZtLessThanOrEqualTo(String value) {
            addCriterion("c_zt <=", value, "cZt");
            return (Criteria) this;
        }

        public Criteria andCZtLike(String value) {
            addCriterion("c_zt like", value, "cZt");
            return (Criteria) this;
        }

        public Criteria andCZtNotLike(String value) {
            addCriterion("c_zt not like", value, "cZt");
            return (Criteria) this;
        }

        public Criteria andCZtIn(List<String> values) {
            addCriterion("c_zt in", values, "cZt");
            return (Criteria) this;
        }

        public Criteria andCZtNotIn(List<String> values) {
            addCriterion("c_zt not in", values, "cZt");
            return (Criteria) this;
        }

        public Criteria andCZtBetween(String value1, String value2) {
            addCriterion("c_zt between", value1, value2, "cZt");
            return (Criteria) this;
        }

        public Criteria andCZtNotBetween(String value1, String value2) {
            addCriterion("c_zt not between", value1, value2, "cZt");
            return (Criteria) this;
        }

        public Criteria andCCjuserIsNull() {
            addCriterion("c_cjuser is null");
            return (Criteria) this;
        }

        public Criteria andCCjuserIsNotNull() {
            addCriterion("c_cjuser is not null");
            return (Criteria) this;
        }

        public Criteria andCCjuserEqualTo(String value) {
            addCriterion("c_cjuser =", value, "cCjuser");
            return (Criteria) this;
        }

        public Criteria andCCjuserNotEqualTo(String value) {
            addCriterion("c_cjuser <>", value, "cCjuser");
            return (Criteria) this;
        }

        public Criteria andCCjuserGreaterThan(String value) {
            addCriterion("c_cjuser >", value, "cCjuser");
            return (Criteria) this;
        }

        public Criteria andCCjuserGreaterThanOrEqualTo(String value) {
            addCriterion("c_cjuser >=", value, "cCjuser");
            return (Criteria) this;
        }

        public Criteria andCCjuserLessThan(String value) {
            addCriterion("c_cjuser <", value, "cCjuser");
            return (Criteria) this;
        }

        public Criteria andCCjuserLessThanOrEqualTo(String value) {
            addCriterion("c_cjuser <=", value, "cCjuser");
            return (Criteria) this;
        }

        public Criteria andCCjuserLike(String value) {
            addCriterion("c_cjuser like", value, "cCjuser");
            return (Criteria) this;
        }

        public Criteria andCCjuserNotLike(String value) {
            addCriterion("c_cjuser not like", value, "cCjuser");
            return (Criteria) this;
        }

        public Criteria andCCjuserIn(List<String> values) {
            addCriterion("c_cjuser in", values, "cCjuser");
            return (Criteria) this;
        }

        public Criteria andCCjuserNotIn(List<String> values) {
            addCriterion("c_cjuser not in", values, "cCjuser");
            return (Criteria) this;
        }

        public Criteria andCCjuserBetween(String value1, String value2) {
            addCriterion("c_cjuser between", value1, value2, "cCjuser");
            return (Criteria) this;
        }

        public Criteria andCCjuserNotBetween(String value1, String value2) {
            addCriterion("c_cjuser not between", value1, value2, "cCjuser");
            return (Criteria) this;
        }

        public Criteria andDCjsjIsNull() {
            addCriterion("d_cjsj is null");
            return (Criteria) this;
        }

        public Criteria andDCjsjIsNotNull() {
            addCriterion("d_cjsj is not null");
            return (Criteria) this;
        }

        public Criteria andDCjsjEqualTo(Date value) {
            addCriterion("d_cjsj =", value, "dCjsj");
            return (Criteria) this;
        }

        public Criteria andDCjsjNotEqualTo(Date value) {
            addCriterion("d_cjsj <>", value, "dCjsj");
            return (Criteria) this;
        }

        public Criteria andDCjsjGreaterThan(Date value) {
            addCriterion("d_cjsj >", value, "dCjsj");
            return (Criteria) this;
        }

        public Criteria andDCjsjGreaterThanOrEqualTo(Date value) {
            addCriterion("d_cjsj >=", value, "dCjsj");
            return (Criteria) this;
        }

        public Criteria andDCjsjLessThan(Date value) {
            addCriterion("d_cjsj <", value, "dCjsj");
            return (Criteria) this;
        }

        public Criteria andDCjsjLessThanOrEqualTo(Date value) {
            addCriterion("d_cjsj <=", value, "dCjsj");
            return (Criteria) this;
        }

        public Criteria andDCjsjIn(List<Date> values) {
            addCriterion("d_cjsj in", values, "dCjsj");
            return (Criteria) this;
        }

        public Criteria andDCjsjNotIn(List<Date> values) {
            addCriterion("d_cjsj not in", values, "dCjsj");
            return (Criteria) this;
        }

        public Criteria andDCjsjBetween(Date value1, Date value2) {
            addCriterion("d_cjsj between", value1, value2, "dCjsj");
            return (Criteria) this;
        }

        public Criteria andDCjsjNotBetween(Date value1, Date value2) {
            addCriterion("d_cjsj not between", value1, value2, "dCjsj");
            return (Criteria) this;
        }

        public Criteria andCXguserIsNull() {
            addCriterion("c_xguser is null");
            return (Criteria) this;
        }

        public Criteria andCXguserIsNotNull() {
            addCriterion("c_xguser is not null");
            return (Criteria) this;
        }

        public Criteria andCXguserEqualTo(String value) {
            addCriterion("c_xguser =", value, "cXguser");
            return (Criteria) this;
        }

        public Criteria andCXguserNotEqualTo(String value) {
            addCriterion("c_xguser <>", value, "cXguser");
            return (Criteria) this;
        }

        public Criteria andCXguserGreaterThan(String value) {
            addCriterion("c_xguser >", value, "cXguser");
            return (Criteria) this;
        }

        public Criteria andCXguserGreaterThanOrEqualTo(String value) {
            addCriterion("c_xguser >=", value, "cXguser");
            return (Criteria) this;
        }

        public Criteria andCXguserLessThan(String value) {
            addCriterion("c_xguser <", value, "cXguser");
            return (Criteria) this;
        }

        public Criteria andCXguserLessThanOrEqualTo(String value) {
            addCriterion("c_xguser <=", value, "cXguser");
            return (Criteria) this;
        }

        public Criteria andCXguserLike(String value) {
            addCriterion("c_xguser like", value, "cXguser");
            return (Criteria) this;
        }

        public Criteria andCXguserNotLike(String value) {
            addCriterion("c_xguser not like", value, "cXguser");
            return (Criteria) this;
        }

        public Criteria andCXguserIn(List<String> values) {
            addCriterion("c_xguser in", values, "cXguser");
            return (Criteria) this;
        }

        public Criteria andCXguserNotIn(List<String> values) {
            addCriterion("c_xguser not in", values, "cXguser");
            return (Criteria) this;
        }

        public Criteria andCXguserBetween(String value1, String value2) {
            addCriterion("c_xguser between", value1, value2, "cXguser");
            return (Criteria) this;
        }

        public Criteria andCXguserNotBetween(String value1, String value2) {
            addCriterion("c_xguser not between", value1, value2, "cXguser");
            return (Criteria) this;
        }

        public Criteria andDXgsjIsNull() {
            addCriterion("d_xgsj is null");
            return (Criteria) this;
        }

        public Criteria andDXgsjIsNotNull() {
            addCriterion("d_xgsj is not null");
            return (Criteria) this;
        }

        public Criteria andDXgsjEqualTo(Date value) {
            addCriterion("d_xgsj =", value, "dXgsj");
            return (Criteria) this;
        }

        public Criteria andDXgsjNotEqualTo(Date value) {
            addCriterion("d_xgsj <>", value, "dXgsj");
            return (Criteria) this;
        }

        public Criteria andDXgsjGreaterThan(Date value) {
            addCriterion("d_xgsj >", value, "dXgsj");
            return (Criteria) this;
        }

        public Criteria andDXgsjGreaterThanOrEqualTo(Date value) {
            addCriterion("d_xgsj >=", value, "dXgsj");
            return (Criteria) this;
        }

        public Criteria andDXgsjLessThan(Date value) {
            addCriterion("d_xgsj <", value, "dXgsj");
            return (Criteria) this;
        }

        public Criteria andDXgsjLessThanOrEqualTo(Date value) {
            addCriterion("d_xgsj <=", value, "dXgsj");
            return (Criteria) this;
        }

        public Criteria andDXgsjIn(List<Date> values) {
            addCriterion("d_xgsj in", values, "dXgsj");
            return (Criteria) this;
        }

        public Criteria andDXgsjNotIn(List<Date> values) {
            addCriterion("d_xgsj not in", values, "dXgsj");
            return (Criteria) this;
        }

        public Criteria andDXgsjBetween(Date value1, Date value2) {
            addCriterion("d_xgsj between", value1, value2, "dXgsj");
            return (Criteria) this;
        }

        public Criteria andDXgsjNotBetween(Date value1, Date value2) {
            addCriterion("d_xgsj not between", value1, value2, "dXgsj");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_green_sp_spmx
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_green_sp_spmx
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}