package com.greenplatform.dao;

import com.greenplatform.model.PlateYwLx;
import com.greenplatform.model.PlateYwLxExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface PlateYwLxMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plate_yw_lx
     *
     * @mbggenerated
     */
    int countByExample(PlateYwLxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plate_yw_lx
     *
     * @mbggenerated
     */
    int deleteByExample(PlateYwLxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plate_yw_lx
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String cYwlxdm);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plate_yw_lx
     *
     * @mbggenerated
     */
    int insert(PlateYwLx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plate_yw_lx
     *
     * @mbggenerated
     */
    int insertSelective(PlateYwLx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plate_yw_lx
     *
     * @mbggenerated
     */
    List<PlateYwLx> selectByExample(PlateYwLxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plate_yw_lx
     *
     * @mbggenerated
     */
    PlateYwLx selectByPrimaryKey(String cYwlxdm);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plate_yw_lx
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PlateYwLx record, @Param("example") PlateYwLxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plate_yw_lx
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") PlateYwLx record, @Param("example") PlateYwLxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plate_yw_lx
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PlateYwLx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plate_yw_lx
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PlateYwLx record);
}