package com.greenplatform.dao;

import com.greenplatform.model.PlateUserPermission;
import com.greenplatform.model.PlateUserPermissionExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface PlateUserPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plate_user_permission
     *
     * @mbggenerated
     */
    int countByExample(PlateUserPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plate_user_permission
     *
     * @mbggenerated
     */
    int deleteByExample(PlateUserPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plate_user_permission
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(@Param("nRole") String nRole, @Param("cMenudm") String cMenudm);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plate_user_permission
     *
     * @mbggenerated
     */
    int insert(PlateUserPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plate_user_permission
     *
     * @mbggenerated
     */
    int insertSelective(PlateUserPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plate_user_permission
     *
     * @mbggenerated
     */
    List<PlateUserPermission> selectByExample(PlateUserPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plate_user_permission
     *
     * @mbggenerated
     */
    PlateUserPermission selectByPrimaryKey(@Param("nRole") String nRole, @Param("cMenudm") String cMenudm);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plate_user_permission
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PlateUserPermission record, @Param("example") PlateUserPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plate_user_permission
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") PlateUserPermission record, @Param("example") PlateUserPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plate_user_permission
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PlateUserPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plate_user_permission
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PlateUserPermission record);
}