package com.greenplatform.dao;

import com.greenplatform.model.PlateUser;
import com.greenplatform.model.PlateUserExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface PlateUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plate_user
     *
     * @mbggenerated
     */
    int countByExample(PlateUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plate_user
     *
     * @mbggenerated
     */
    int deleteByExample(PlateUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plate_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer cUserid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plate_user
     *
     * @mbggenerated
     */
    int insert(PlateUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plate_user
     *
     * @mbggenerated
     */
    int insertSelective(PlateUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plate_user
     *
     * @mbggenerated
     */
    List<PlateUser> selectByExample(PlateUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plate_user
     *
     * @mbggenerated
     */
    PlateUser selectByPrimaryKey(Integer cUserid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plate_user
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PlateUser record, @Param("example") PlateUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plate_user
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") PlateUser record, @Param("example") PlateUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plate_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PlateUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plate_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PlateUser record);
}