package com.plate.publicmag.dao;

import com.plate.publicmag.model.TSystemMenu;
import com.plate.publicmag.model.TSystemMenuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TSystemMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_menu
     *
     * @mbggenerated
     */
    int countByExample(TSystemMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_menu
     *
     * @mbggenerated
     */
    int deleteByExample(TSystemMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_menu
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_menu
     *
     * @mbggenerated
     */
    int insert(TSystemMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_menu
     *
     * @mbggenerated
     */
    int insertSelective(TSystemMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_menu
     *
     * @mbggenerated
     */
    List<TSystemMenu> selectByExample(TSystemMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_menu
     *
     * @mbggenerated
     */
    TSystemMenu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_menu
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TSystemMenu record, @Param("example") TSystemMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_menu
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TSystemMenu record, @Param("example") TSystemMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_menu
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TSystemMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_menu
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TSystemMenu record);
}