package com.greenplatform.model;

import java.io.Serializable;
import java.util.Date;

public class PlateUser implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plate_user.c_Userid
     *
     * @mbggenerated
     */
    private String cUserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plate_user.c_Loginname
     *
     * @mbggenerated
     */
    private String cLoginname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plate_user.c_Username
     *
     * @mbggenerated
     */
    private String cUsername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plate_user.cSex
     *
     * @mbggenerated
     */
    private String csex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plate_user.cPassword
     *
     * @mbggenerated
     */
    private String cpassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plate_user.cRydj
     *
     * @mbggenerated
     */
    private String crydj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plate_user.cRylb
     *
     * @mbggenerated
     */
    private String crylb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plate_user.cRyzt
     *
     * @mbggenerated
     */
    private String cryzt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plate_user.cRyxz
     *
     * @mbggenerated
     */
    private String cryxz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plate_user.cZcfs
     *
     * @mbggenerated
     */
    private String czcfs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plate_user.cZjlx
     *
     * @mbggenerated
     */
    private String czjlx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plate_user.cZjhm
     *
     * @mbggenerated
     */
    private String czjhm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plate_user.cJtzz
     *
     * @mbggenerated
     */
    private String cjtzz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plate_user.cPhone
     *
     * @mbggenerated
     */
    private String cphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plate_user.cWxhm
     *
     * @mbggenerated
     */
    private String cwxhm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plate_user.cQq
     *
     * @mbggenerated
     */
    private String cqq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plate_user.cEmail
     *
     * @mbggenerated
     */
    private String cemail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plate_user.cBz
     *
     * @mbggenerated
     */
    private String cbz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plate_user.cZt
     *
     * @mbggenerated
     */
    private String czt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plate_user.cCjuser
     *
     * @mbggenerated
     */
    private String ccjuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plate_user.dCjsj
     *
     * @mbggenerated
     */
    private Date dcjsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plate_user.cXguser
     *
     * @mbggenerated
     */
    private String cxguser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plate_user.dXgsj
     *
     * @mbggenerated
     */
    private Date dxgsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table plate_user
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plate_user.c_Userid
     *
     * @return the value of plate_user.c_Userid
     *
     * @mbggenerated
     */
    public String getcUserid() {
        return cUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plate_user.c_Userid
     *
     * @param cUserid the value for plate_user.c_Userid
     *
     * @mbggenerated
     */
    public void setcUserid(String cUserid) {
        this.cUserid = cUserid == null ? null : cUserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plate_user.c_Loginname
     *
     * @return the value of plate_user.c_Loginname
     *
     * @mbggenerated
     */
    public String getcLoginname() {
        return cLoginname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plate_user.c_Loginname
     *
     * @param cLoginname the value for plate_user.c_Loginname
     *
     * @mbggenerated
     */
    public void setcLoginname(String cLoginname) {
        this.cLoginname = cLoginname == null ? null : cLoginname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plate_user.c_Username
     *
     * @return the value of plate_user.c_Username
     *
     * @mbggenerated
     */
    public String getcUsername() {
        return cUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plate_user.c_Username
     *
     * @param cUsername the value for plate_user.c_Username
     *
     * @mbggenerated
     */
    public void setcUsername(String cUsername) {
        this.cUsername = cUsername == null ? null : cUsername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plate_user.cSex
     *
     * @return the value of plate_user.cSex
     *
     * @mbggenerated
     */
    public String getCsex() {
        return csex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plate_user.cSex
     *
     * @param csex the value for plate_user.cSex
     *
     * @mbggenerated
     */
    public void setCsex(String csex) {
        this.csex = csex == null ? null : csex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plate_user.cPassword
     *
     * @return the value of plate_user.cPassword
     *
     * @mbggenerated
     */
    public String getCpassword() {
        return cpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plate_user.cPassword
     *
     * @param cpassword the value for plate_user.cPassword
     *
     * @mbggenerated
     */
    public void setCpassword(String cpassword) {
        this.cpassword = cpassword == null ? null : cpassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plate_user.cRydj
     *
     * @return the value of plate_user.cRydj
     *
     * @mbggenerated
     */
    public String getCrydj() {
        return crydj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plate_user.cRydj
     *
     * @param crydj the value for plate_user.cRydj
     *
     * @mbggenerated
     */
    public void setCrydj(String crydj) {
        this.crydj = crydj == null ? null : crydj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plate_user.cRylb
     *
     * @return the value of plate_user.cRylb
     *
     * @mbggenerated
     */
    public String getCrylb() {
        return crylb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plate_user.cRylb
     *
     * @param crylb the value for plate_user.cRylb
     *
     * @mbggenerated
     */
    public void setCrylb(String crylb) {
        this.crylb = crylb == null ? null : crylb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plate_user.cRyzt
     *
     * @return the value of plate_user.cRyzt
     *
     * @mbggenerated
     */
    public String getCryzt() {
        return cryzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plate_user.cRyzt
     *
     * @param cryzt the value for plate_user.cRyzt
     *
     * @mbggenerated
     */
    public void setCryzt(String cryzt) {
        this.cryzt = cryzt == null ? null : cryzt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plate_user.cRyxz
     *
     * @return the value of plate_user.cRyxz
     *
     * @mbggenerated
     */
    public String getCryxz() {
        return cryxz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plate_user.cRyxz
     *
     * @param cryxz the value for plate_user.cRyxz
     *
     * @mbggenerated
     */
    public void setCryxz(String cryxz) {
        this.cryxz = cryxz == null ? null : cryxz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plate_user.cZcfs
     *
     * @return the value of plate_user.cZcfs
     *
     * @mbggenerated
     */
    public String getCzcfs() {
        return czcfs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plate_user.cZcfs
     *
     * @param czcfs the value for plate_user.cZcfs
     *
     * @mbggenerated
     */
    public void setCzcfs(String czcfs) {
        this.czcfs = czcfs == null ? null : czcfs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plate_user.cZjlx
     *
     * @return the value of plate_user.cZjlx
     *
     * @mbggenerated
     */
    public String getCzjlx() {
        return czjlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plate_user.cZjlx
     *
     * @param czjlx the value for plate_user.cZjlx
     *
     * @mbggenerated
     */
    public void setCzjlx(String czjlx) {
        this.czjlx = czjlx == null ? null : czjlx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plate_user.cZjhm
     *
     * @return the value of plate_user.cZjhm
     *
     * @mbggenerated
     */
    public String getCzjhm() {
        return czjhm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plate_user.cZjhm
     *
     * @param czjhm the value for plate_user.cZjhm
     *
     * @mbggenerated
     */
    public void setCzjhm(String czjhm) {
        this.czjhm = czjhm == null ? null : czjhm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plate_user.cJtzz
     *
     * @return the value of plate_user.cJtzz
     *
     * @mbggenerated
     */
    public String getCjtzz() {
        return cjtzz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plate_user.cJtzz
     *
     * @param cjtzz the value for plate_user.cJtzz
     *
     * @mbggenerated
     */
    public void setCjtzz(String cjtzz) {
        this.cjtzz = cjtzz == null ? null : cjtzz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plate_user.cPhone
     *
     * @return the value of plate_user.cPhone
     *
     * @mbggenerated
     */
    public String getCphone() {
        return cphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plate_user.cPhone
     *
     * @param cphone the value for plate_user.cPhone
     *
     * @mbggenerated
     */
    public void setCphone(String cphone) {
        this.cphone = cphone == null ? null : cphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plate_user.cWxhm
     *
     * @return the value of plate_user.cWxhm
     *
     * @mbggenerated
     */
    public String getCwxhm() {
        return cwxhm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plate_user.cWxhm
     *
     * @param cwxhm the value for plate_user.cWxhm
     *
     * @mbggenerated
     */
    public void setCwxhm(String cwxhm) {
        this.cwxhm = cwxhm == null ? null : cwxhm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plate_user.cQq
     *
     * @return the value of plate_user.cQq
     *
     * @mbggenerated
     */
    public String getCqq() {
        return cqq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plate_user.cQq
     *
     * @param cqq the value for plate_user.cQq
     *
     * @mbggenerated
     */
    public void setCqq(String cqq) {
        this.cqq = cqq == null ? null : cqq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plate_user.cEmail
     *
     * @return the value of plate_user.cEmail
     *
     * @mbggenerated
     */
    public String getCemail() {
        return cemail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plate_user.cEmail
     *
     * @param cemail the value for plate_user.cEmail
     *
     * @mbggenerated
     */
    public void setCemail(String cemail) {
        this.cemail = cemail == null ? null : cemail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plate_user.cBz
     *
     * @return the value of plate_user.cBz
     *
     * @mbggenerated
     */
    public String getCbz() {
        return cbz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plate_user.cBz
     *
     * @param cbz the value for plate_user.cBz
     *
     * @mbggenerated
     */
    public void setCbz(String cbz) {
        this.cbz = cbz == null ? null : cbz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plate_user.cZt
     *
     * @return the value of plate_user.cZt
     *
     * @mbggenerated
     */
    public String getCzt() {
        return czt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plate_user.cZt
     *
     * @param czt the value for plate_user.cZt
     *
     * @mbggenerated
     */
    public void setCzt(String czt) {
        this.czt = czt == null ? null : czt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plate_user.cCjuser
     *
     * @return the value of plate_user.cCjuser
     *
     * @mbggenerated
     */
    public String getCcjuser() {
        return ccjuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plate_user.cCjuser
     *
     * @param ccjuser the value for plate_user.cCjuser
     *
     * @mbggenerated
     */
    public void setCcjuser(String ccjuser) {
        this.ccjuser = ccjuser == null ? null : ccjuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plate_user.dCjsj
     *
     * @return the value of plate_user.dCjsj
     *
     * @mbggenerated
     */
    public Date getDcjsj() {
        return dcjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plate_user.dCjsj
     *
     * @param dcjsj the value for plate_user.dCjsj
     *
     * @mbggenerated
     */
    public void setDcjsj(Date dcjsj) {
        this.dcjsj = dcjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plate_user.cXguser
     *
     * @return the value of plate_user.cXguser
     *
     * @mbggenerated
     */
    public String getCxguser() {
        return cxguser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plate_user.cXguser
     *
     * @param cxguser the value for plate_user.cXguser
     *
     * @mbggenerated
     */
    public void setCxguser(String cxguser) {
        this.cxguser = cxguser == null ? null : cxguser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plate_user.dXgsj
     *
     * @return the value of plate_user.dXgsj
     *
     * @mbggenerated
     */
    public Date getDxgsj() {
        return dxgsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plate_user.dXgsj
     *
     * @param dxgsj the value for plate_user.dXgsj
     *
     * @mbggenerated
     */
    public void setDxgsj(Date dxgsj) {
        this.dxgsj = dxgsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plate_user
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", cUserid=").append(cUserid);
        sb.append(", cLoginname=").append(cLoginname);
        sb.append(", cUsername=").append(cUsername);
        sb.append(", csex=").append(csex);
        sb.append(", cpassword=").append(cpassword);
        sb.append(", crydj=").append(crydj);
        sb.append(", crylb=").append(crylb);
        sb.append(", cryzt=").append(cryzt);
        sb.append(", cryxz=").append(cryxz);
        sb.append(", czcfs=").append(czcfs);
        sb.append(", czjlx=").append(czjlx);
        sb.append(", czjhm=").append(czjhm);
        sb.append(", cjtzz=").append(cjtzz);
        sb.append(", cphone=").append(cphone);
        sb.append(", cwxhm=").append(cwxhm);
        sb.append(", cqq=").append(cqq);
        sb.append(", cemail=").append(cemail);
        sb.append(", cbz=").append(cbz);
        sb.append(", czt=").append(czt);
        sb.append(", ccjuser=").append(ccjuser);
        sb.append(", dcjsj=").append(dcjsj);
        sb.append(", cxguser=").append(cxguser);
        sb.append(", dxgsj=").append(dxgsj);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}