package com.greenplatform.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PlateUserBlacklistExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table plate_user_blacklist
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table plate_user_blacklist
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table plate_user_blacklist
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plate_user_blacklist
     *
     * @mbggenerated
     */
    public PlateUserBlacklistExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plate_user_blacklist
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plate_user_blacklist
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plate_user_blacklist
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plate_user_blacklist
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plate_user_blacklist
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plate_user_blacklist
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plate_user_blacklist
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plate_user_blacklist
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plate_user_blacklist
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plate_user_blacklist
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table plate_user_blacklist
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCLshIsNull() {
            addCriterion("c_lsh is null");
            return (Criteria) this;
        }

        public Criteria andCLshIsNotNull() {
            addCriterion("c_lsh is not null");
            return (Criteria) this;
        }

        public Criteria andCLshEqualTo(String value) {
            addCriterion("c_lsh =", value, "cLsh");
            return (Criteria) this;
        }

        public Criteria andCLshNotEqualTo(String value) {
            addCriterion("c_lsh <>", value, "cLsh");
            return (Criteria) this;
        }

        public Criteria andCLshGreaterThan(String value) {
            addCriterion("c_lsh >", value, "cLsh");
            return (Criteria) this;
        }

        public Criteria andCLshGreaterThanOrEqualTo(String value) {
            addCriterion("c_lsh >=", value, "cLsh");
            return (Criteria) this;
        }

        public Criteria andCLshLessThan(String value) {
            addCriterion("c_lsh <", value, "cLsh");
            return (Criteria) this;
        }

        public Criteria andCLshLessThanOrEqualTo(String value) {
            addCriterion("c_lsh <=", value, "cLsh");
            return (Criteria) this;
        }

        public Criteria andCLshLike(String value) {
            addCriterion("c_lsh like", value, "cLsh");
            return (Criteria) this;
        }

        public Criteria andCLshNotLike(String value) {
            addCriterion("c_lsh not like", value, "cLsh");
            return (Criteria) this;
        }

        public Criteria andCLshIn(List<String> values) {
            addCriterion("c_lsh in", values, "cLsh");
            return (Criteria) this;
        }

        public Criteria andCLshNotIn(List<String> values) {
            addCriterion("c_lsh not in", values, "cLsh");
            return (Criteria) this;
        }

        public Criteria andCLshBetween(String value1, String value2) {
            addCriterion("c_lsh between", value1, value2, "cLsh");
            return (Criteria) this;
        }

        public Criteria andCLshNotBetween(String value1, String value2) {
            addCriterion("c_lsh not between", value1, value2, "cLsh");
            return (Criteria) this;
        }

        public Criteria andCUseridIsNull() {
            addCriterion("c_userid is null");
            return (Criteria) this;
        }

        public Criteria andCUseridIsNotNull() {
            addCriterion("c_userid is not null");
            return (Criteria) this;
        }

        public Criteria andCUseridEqualTo(String value) {
            addCriterion("c_userid =", value, "cUserid");
            return (Criteria) this;
        }

        public Criteria andCUseridNotEqualTo(String value) {
            addCriterion("c_userid <>", value, "cUserid");
            return (Criteria) this;
        }

        public Criteria andCUseridGreaterThan(String value) {
            addCriterion("c_userid >", value, "cUserid");
            return (Criteria) this;
        }

        public Criteria andCUseridGreaterThanOrEqualTo(String value) {
            addCriterion("c_userid >=", value, "cUserid");
            return (Criteria) this;
        }

        public Criteria andCUseridLessThan(String value) {
            addCriterion("c_userid <", value, "cUserid");
            return (Criteria) this;
        }

        public Criteria andCUseridLessThanOrEqualTo(String value) {
            addCriterion("c_userid <=", value, "cUserid");
            return (Criteria) this;
        }

        public Criteria andCUseridLike(String value) {
            addCriterion("c_userid like", value, "cUserid");
            return (Criteria) this;
        }

        public Criteria andCUseridNotLike(String value) {
            addCriterion("c_userid not like", value, "cUserid");
            return (Criteria) this;
        }

        public Criteria andCUseridIn(List<String> values) {
            addCriterion("c_userid in", values, "cUserid");
            return (Criteria) this;
        }

        public Criteria andCUseridNotIn(List<String> values) {
            addCriterion("c_userid not in", values, "cUserid");
            return (Criteria) this;
        }

        public Criteria andCUseridBetween(String value1, String value2) {
            addCriterion("c_userid between", value1, value2, "cUserid");
            return (Criteria) this;
        }

        public Criteria andCUseridNotBetween(String value1, String value2) {
            addCriterion("c_userid not between", value1, value2, "cUserid");
            return (Criteria) this;
        }

        public Criteria andCCzfsIsNull() {
            addCriterion("c_czfs is null");
            return (Criteria) this;
        }

        public Criteria andCCzfsIsNotNull() {
            addCriterion("c_czfs is not null");
            return (Criteria) this;
        }

        public Criteria andCCzfsEqualTo(String value) {
            addCriterion("c_czfs =", value, "cCzfs");
            return (Criteria) this;
        }

        public Criteria andCCzfsNotEqualTo(String value) {
            addCriterion("c_czfs <>", value, "cCzfs");
            return (Criteria) this;
        }

        public Criteria andCCzfsGreaterThan(String value) {
            addCriterion("c_czfs >", value, "cCzfs");
            return (Criteria) this;
        }

        public Criteria andCCzfsGreaterThanOrEqualTo(String value) {
            addCriterion("c_czfs >=", value, "cCzfs");
            return (Criteria) this;
        }

        public Criteria andCCzfsLessThan(String value) {
            addCriterion("c_czfs <", value, "cCzfs");
            return (Criteria) this;
        }

        public Criteria andCCzfsLessThanOrEqualTo(String value) {
            addCriterion("c_czfs <=", value, "cCzfs");
            return (Criteria) this;
        }

        public Criteria andCCzfsLike(String value) {
            addCriterion("c_czfs like", value, "cCzfs");
            return (Criteria) this;
        }

        public Criteria andCCzfsNotLike(String value) {
            addCriterion("c_czfs not like", value, "cCzfs");
            return (Criteria) this;
        }

        public Criteria andCCzfsIn(List<String> values) {
            addCriterion("c_czfs in", values, "cCzfs");
            return (Criteria) this;
        }

        public Criteria andCCzfsNotIn(List<String> values) {
            addCriterion("c_czfs not in", values, "cCzfs");
            return (Criteria) this;
        }

        public Criteria andCCzfsBetween(String value1, String value2) {
            addCriterion("c_czfs between", value1, value2, "cCzfs");
            return (Criteria) this;
        }

        public Criteria andCCzfsNotBetween(String value1, String value2) {
            addCriterion("c_czfs not between", value1, value2, "cCzfs");
            return (Criteria) this;
        }

        public Criteria andCCzrIsNull() {
            addCriterion("c_czr is null");
            return (Criteria) this;
        }

        public Criteria andCCzrIsNotNull() {
            addCriterion("c_czr is not null");
            return (Criteria) this;
        }

        public Criteria andCCzrEqualTo(String value) {
            addCriterion("c_czr =", value, "cCzr");
            return (Criteria) this;
        }

        public Criteria andCCzrNotEqualTo(String value) {
            addCriterion("c_czr <>", value, "cCzr");
            return (Criteria) this;
        }

        public Criteria andCCzrGreaterThan(String value) {
            addCriterion("c_czr >", value, "cCzr");
            return (Criteria) this;
        }

        public Criteria andCCzrGreaterThanOrEqualTo(String value) {
            addCriterion("c_czr >=", value, "cCzr");
            return (Criteria) this;
        }

        public Criteria andCCzrLessThan(String value) {
            addCriterion("c_czr <", value, "cCzr");
            return (Criteria) this;
        }

        public Criteria andCCzrLessThanOrEqualTo(String value) {
            addCriterion("c_czr <=", value, "cCzr");
            return (Criteria) this;
        }

        public Criteria andCCzrLike(String value) {
            addCriterion("c_czr like", value, "cCzr");
            return (Criteria) this;
        }

        public Criteria andCCzrNotLike(String value) {
            addCriterion("c_czr not like", value, "cCzr");
            return (Criteria) this;
        }

        public Criteria andCCzrIn(List<String> values) {
            addCriterion("c_czr in", values, "cCzr");
            return (Criteria) this;
        }

        public Criteria andCCzrNotIn(List<String> values) {
            addCriterion("c_czr not in", values, "cCzr");
            return (Criteria) this;
        }

        public Criteria andCCzrBetween(String value1, String value2) {
            addCriterion("c_czr between", value1, value2, "cCzr");
            return (Criteria) this;
        }

        public Criteria andCCzrNotBetween(String value1, String value2) {
            addCriterion("c_czr not between", value1, value2, "cCzr");
            return (Criteria) this;
        }

        public Criteria andDCzsjIsNull() {
            addCriterion("d_czsj is null");
            return (Criteria) this;
        }

        public Criteria andDCzsjIsNotNull() {
            addCriterion("d_czsj is not null");
            return (Criteria) this;
        }

        public Criteria andDCzsjEqualTo(Date value) {
            addCriterion("d_czsj =", value, "dCzsj");
            return (Criteria) this;
        }

        public Criteria andDCzsjNotEqualTo(Date value) {
            addCriterion("d_czsj <>", value, "dCzsj");
            return (Criteria) this;
        }

        public Criteria andDCzsjGreaterThan(Date value) {
            addCriterion("d_czsj >", value, "dCzsj");
            return (Criteria) this;
        }

        public Criteria andDCzsjGreaterThanOrEqualTo(Date value) {
            addCriterion("d_czsj >=", value, "dCzsj");
            return (Criteria) this;
        }

        public Criteria andDCzsjLessThan(Date value) {
            addCriterion("d_czsj <", value, "dCzsj");
            return (Criteria) this;
        }

        public Criteria andDCzsjLessThanOrEqualTo(Date value) {
            addCriterion("d_czsj <=", value, "dCzsj");
            return (Criteria) this;
        }

        public Criteria andDCzsjIn(List<Date> values) {
            addCriterion("d_czsj in", values, "dCzsj");
            return (Criteria) this;
        }

        public Criteria andDCzsjNotIn(List<Date> values) {
            addCriterion("d_czsj not in", values, "dCzsj");
            return (Criteria) this;
        }

        public Criteria andDCzsjBetween(Date value1, Date value2) {
            addCriterion("d_czsj between", value1, value2, "dCzsj");
            return (Criteria) this;
        }

        public Criteria andDCzsjNotBetween(Date value1, Date value2) {
            addCriterion("d_czsj not between", value1, value2, "dCzsj");
            return (Criteria) this;
        }

        public Criteria andCCzyyIsNull() {
            addCriterion("c_czyy is null");
            return (Criteria) this;
        }

        public Criteria andCCzyyIsNotNull() {
            addCriterion("c_czyy is not null");
            return (Criteria) this;
        }

        public Criteria andCCzyyEqualTo(String value) {
            addCriterion("c_czyy =", value, "cCzyy");
            return (Criteria) this;
        }

        public Criteria andCCzyyNotEqualTo(String value) {
            addCriterion("c_czyy <>", value, "cCzyy");
            return (Criteria) this;
        }

        public Criteria andCCzyyGreaterThan(String value) {
            addCriterion("c_czyy >", value, "cCzyy");
            return (Criteria) this;
        }

        public Criteria andCCzyyGreaterThanOrEqualTo(String value) {
            addCriterion("c_czyy >=", value, "cCzyy");
            return (Criteria) this;
        }

        public Criteria andCCzyyLessThan(String value) {
            addCriterion("c_czyy <", value, "cCzyy");
            return (Criteria) this;
        }

        public Criteria andCCzyyLessThanOrEqualTo(String value) {
            addCriterion("c_czyy <=", value, "cCzyy");
            return (Criteria) this;
        }

        public Criteria andCCzyyLike(String value) {
            addCriterion("c_czyy like", value, "cCzyy");
            return (Criteria) this;
        }

        public Criteria andCCzyyNotLike(String value) {
            addCriterion("c_czyy not like", value, "cCzyy");
            return (Criteria) this;
        }

        public Criteria andCCzyyIn(List<String> values) {
            addCriterion("c_czyy in", values, "cCzyy");
            return (Criteria) this;
        }

        public Criteria andCCzyyNotIn(List<String> values) {
            addCriterion("c_czyy not in", values, "cCzyy");
            return (Criteria) this;
        }

        public Criteria andCCzyyBetween(String value1, String value2) {
            addCriterion("c_czyy between", value1, value2, "cCzyy");
            return (Criteria) this;
        }

        public Criteria andCCzyyNotBetween(String value1, String value2) {
            addCriterion("c_czyy not between", value1, value2, "cCzyy");
            return (Criteria) this;
        }

        public Criteria andCZtIsNull() {
            addCriterion("c_zt is null");
            return (Criteria) this;
        }

        public Criteria andCZtIsNotNull() {
            addCriterion("c_zt is not null");
            return (Criteria) this;
        }

        public Criteria andCZtEqualTo(String value) {
            addCriterion("c_zt =", value, "cZt");
            return (Criteria) this;
        }

        public Criteria andCZtNotEqualTo(String value) {
            addCriterion("c_zt <>", value, "cZt");
            return (Criteria) this;
        }

        public Criteria andCZtGreaterThan(String value) {
            addCriterion("c_zt >", value, "cZt");
            return (Criteria) this;
        }

        public Criteria andCZtGreaterThanOrEqualTo(String value) {
            addCriterion("c_zt >=", value, "cZt");
            return (Criteria) this;
        }

        public Criteria andCZtLessThan(String value) {
            addCriterion("c_zt <", value, "cZt");
            return (Criteria) this;
        }

        public Criteria andCZtLessThanOrEqualTo(String value) {
            addCriterion("c_zt <=", value, "cZt");
            return (Criteria) this;
        }

        public Criteria andCZtLike(String value) {
            addCriterion("c_zt like", value, "cZt");
            return (Criteria) this;
        }

        public Criteria andCZtNotLike(String value) {
            addCriterion("c_zt not like", value, "cZt");
            return (Criteria) this;
        }

        public Criteria andCZtIn(List<String> values) {
            addCriterion("c_zt in", values, "cZt");
            return (Criteria) this;
        }

        public Criteria andCZtNotIn(List<String> values) {
            addCriterion("c_zt not in", values, "cZt");
            return (Criteria) this;
        }

        public Criteria andCZtBetween(String value1, String value2) {
            addCriterion("c_zt between", value1, value2, "cZt");
            return (Criteria) this;
        }

        public Criteria andCZtNotBetween(String value1, String value2) {
            addCriterion("c_zt not between", value1, value2, "cZt");
            return (Criteria) this;
        }

        public Criteria andCCjuserIsNull() {
            addCriterion("c_cjuser is null");
            return (Criteria) this;
        }

        public Criteria andCCjuserIsNotNull() {
            addCriterion("c_cjuser is not null");
            return (Criteria) this;
        }

        public Criteria andCCjuserEqualTo(String value) {
            addCriterion("c_cjuser =", value, "cCjuser");
            return (Criteria) this;
        }

        public Criteria andCCjuserNotEqualTo(String value) {
            addCriterion("c_cjuser <>", value, "cCjuser");
            return (Criteria) this;
        }

        public Criteria andCCjuserGreaterThan(String value) {
            addCriterion("c_cjuser >", value, "cCjuser");
            return (Criteria) this;
        }

        public Criteria andCCjuserGreaterThanOrEqualTo(String value) {
            addCriterion("c_cjuser >=", value, "cCjuser");
            return (Criteria) this;
        }

        public Criteria andCCjuserLessThan(String value) {
            addCriterion("c_cjuser <", value, "cCjuser");
            return (Criteria) this;
        }

        public Criteria andCCjuserLessThanOrEqualTo(String value) {
            addCriterion("c_cjuser <=", value, "cCjuser");
            return (Criteria) this;
        }

        public Criteria andCCjuserLike(String value) {
            addCriterion("c_cjuser like", value, "cCjuser");
            return (Criteria) this;
        }

        public Criteria andCCjuserNotLike(String value) {
            addCriterion("c_cjuser not like", value, "cCjuser");
            return (Criteria) this;
        }

        public Criteria andCCjuserIn(List<String> values) {
            addCriterion("c_cjuser in", values, "cCjuser");
            return (Criteria) this;
        }

        public Criteria andCCjuserNotIn(List<String> values) {
            addCriterion("c_cjuser not in", values, "cCjuser");
            return (Criteria) this;
        }

        public Criteria andCCjuserBetween(String value1, String value2) {
            addCriterion("c_cjuser between", value1, value2, "cCjuser");
            return (Criteria) this;
        }

        public Criteria andCCjuserNotBetween(String value1, String value2) {
            addCriterion("c_cjuser not between", value1, value2, "cCjuser");
            return (Criteria) this;
        }

        public Criteria andDCjsjIsNull() {
            addCriterion("d_cjsj is null");
            return (Criteria) this;
        }

        public Criteria andDCjsjIsNotNull() {
            addCriterion("d_cjsj is not null");
            return (Criteria) this;
        }

        public Criteria andDCjsjEqualTo(Date value) {
            addCriterion("d_cjsj =", value, "dCjsj");
            return (Criteria) this;
        }

        public Criteria andDCjsjNotEqualTo(Date value) {
            addCriterion("d_cjsj <>", value, "dCjsj");
            return (Criteria) this;
        }

        public Criteria andDCjsjGreaterThan(Date value) {
            addCriterion("d_cjsj >", value, "dCjsj");
            return (Criteria) this;
        }

        public Criteria andDCjsjGreaterThanOrEqualTo(Date value) {
            addCriterion("d_cjsj >=", value, "dCjsj");
            return (Criteria) this;
        }

        public Criteria andDCjsjLessThan(Date value) {
            addCriterion("d_cjsj <", value, "dCjsj");
            return (Criteria) this;
        }

        public Criteria andDCjsjLessThanOrEqualTo(Date value) {
            addCriterion("d_cjsj <=", value, "dCjsj");
            return (Criteria) this;
        }

        public Criteria andDCjsjIn(List<Date> values) {
            addCriterion("d_cjsj in", values, "dCjsj");
            return (Criteria) this;
        }

        public Criteria andDCjsjNotIn(List<Date> values) {
            addCriterion("d_cjsj not in", values, "dCjsj");
            return (Criteria) this;
        }

        public Criteria andDCjsjBetween(Date value1, Date value2) {
            addCriterion("d_cjsj between", value1, value2, "dCjsj");
            return (Criteria) this;
        }

        public Criteria andDCjsjNotBetween(Date value1, Date value2) {
            addCriterion("d_cjsj not between", value1, value2, "dCjsj");
            return (Criteria) this;
        }

        public Criteria andCXguserIsNull() {
            addCriterion("c_xguser is null");
            return (Criteria) this;
        }

        public Criteria andCXguserIsNotNull() {
            addCriterion("c_xguser is not null");
            return (Criteria) this;
        }

        public Criteria andCXguserEqualTo(String value) {
            addCriterion("c_xguser =", value, "cXguser");
            return (Criteria) this;
        }

        public Criteria andCXguserNotEqualTo(String value) {
            addCriterion("c_xguser <>", value, "cXguser");
            return (Criteria) this;
        }

        public Criteria andCXguserGreaterThan(String value) {
            addCriterion("c_xguser >", value, "cXguser");
            return (Criteria) this;
        }

        public Criteria andCXguserGreaterThanOrEqualTo(String value) {
            addCriterion("c_xguser >=", value, "cXguser");
            return (Criteria) this;
        }

        public Criteria andCXguserLessThan(String value) {
            addCriterion("c_xguser <", value, "cXguser");
            return (Criteria) this;
        }

        public Criteria andCXguserLessThanOrEqualTo(String value) {
            addCriterion("c_xguser <=", value, "cXguser");
            return (Criteria) this;
        }

        public Criteria andCXguserLike(String value) {
            addCriterion("c_xguser like", value, "cXguser");
            return (Criteria) this;
        }

        public Criteria andCXguserNotLike(String value) {
            addCriterion("c_xguser not like", value, "cXguser");
            return (Criteria) this;
        }

        public Criteria andCXguserIn(List<String> values) {
            addCriterion("c_xguser in", values, "cXguser");
            return (Criteria) this;
        }

        public Criteria andCXguserNotIn(List<String> values) {
            addCriterion("c_xguser not in", values, "cXguser");
            return (Criteria) this;
        }

        public Criteria andCXguserBetween(String value1, String value2) {
            addCriterion("c_xguser between", value1, value2, "cXguser");
            return (Criteria) this;
        }

        public Criteria andCXguserNotBetween(String value1, String value2) {
            addCriterion("c_xguser not between", value1, value2, "cXguser");
            return (Criteria) this;
        }

        public Criteria andDXgsjIsNull() {
            addCriterion("d_xgsj is null");
            return (Criteria) this;
        }

        public Criteria andDXgsjIsNotNull() {
            addCriterion("d_xgsj is not null");
            return (Criteria) this;
        }

        public Criteria andDXgsjEqualTo(Date value) {
            addCriterion("d_xgsj =", value, "dXgsj");
            return (Criteria) this;
        }

        public Criteria andDXgsjNotEqualTo(Date value) {
            addCriterion("d_xgsj <>", value, "dXgsj");
            return (Criteria) this;
        }

        public Criteria andDXgsjGreaterThan(Date value) {
            addCriterion("d_xgsj >", value, "dXgsj");
            return (Criteria) this;
        }

        public Criteria andDXgsjGreaterThanOrEqualTo(Date value) {
            addCriterion("d_xgsj >=", value, "dXgsj");
            return (Criteria) this;
        }

        public Criteria andDXgsjLessThan(Date value) {
            addCriterion("d_xgsj <", value, "dXgsj");
            return (Criteria) this;
        }

        public Criteria andDXgsjLessThanOrEqualTo(Date value) {
            addCriterion("d_xgsj <=", value, "dXgsj");
            return (Criteria) this;
        }

        public Criteria andDXgsjIn(List<Date> values) {
            addCriterion("d_xgsj in", values, "dXgsj");
            return (Criteria) this;
        }

        public Criteria andDXgsjNotIn(List<Date> values) {
            addCriterion("d_xgsj not in", values, "dXgsj");
            return (Criteria) this;
        }

        public Criteria andDXgsjBetween(Date value1, Date value2) {
            addCriterion("d_xgsj between", value1, value2, "dXgsj");
            return (Criteria) this;
        }

        public Criteria andDXgsjNotBetween(Date value1, Date value2) {
            addCriterion("d_xgsj not between", value1, value2, "dXgsj");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table plate_user_blacklist
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table plate_user_blacklist
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}