package com.greenplatform.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class TGreenSpSpmx implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_green_sp_spmx.c_spbh
     *
     * @mbggenerated
     */
    private String cSpbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_green_sp_spmx.c_spmc
     *
     * @mbggenerated
     */
    private String cSpmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_green_sp_spmx.c_spms
     *
     * @mbggenerated
     */
    private String cSpms;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_green_sp_spmx.n_spjg
     *
     * @mbggenerated
     */
    private BigDecimal nSpjg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_green_sp_spmx.c_spdw
     *
     * @mbggenerated
     */
    private String cSpdw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_green_sp_spmx.c_bz
     *
     * @mbggenerated
     */
    private String cBz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_green_sp_spmx.c_zt
     *
     * @mbggenerated
     */
    private String cZt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_green_sp_spmx.c_cjuser
     *
     * @mbggenerated
     */
    private String cCjuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_green_sp_spmx.d_cjsj
     *
     * @mbggenerated
     */
    private Date dCjsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_green_sp_spmx.c_xguser
     *
     * @mbggenerated
     */
    private String cXguser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_green_sp_spmx.d_xgsj
     *
     * @mbggenerated
     */
    private Date dXgsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_green_sp_spmx
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_green_sp_spmx.c_spbh
     *
     * @return the value of t_green_sp_spmx.c_spbh
     *
     * @mbggenerated
     */
    public String getcSpbh() {
        return cSpbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_green_sp_spmx.c_spbh
     *
     * @param cSpbh the value for t_green_sp_spmx.c_spbh
     *
     * @mbggenerated
     */
    public void setcSpbh(String cSpbh) {
        this.cSpbh = cSpbh == null ? null : cSpbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_green_sp_spmx.c_spmc
     *
     * @return the value of t_green_sp_spmx.c_spmc
     *
     * @mbggenerated
     */
    public String getcSpmc() {
        return cSpmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_green_sp_spmx.c_spmc
     *
     * @param cSpmc the value for t_green_sp_spmx.c_spmc
     *
     * @mbggenerated
     */
    public void setcSpmc(String cSpmc) {
        this.cSpmc = cSpmc == null ? null : cSpmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_green_sp_spmx.c_spms
     *
     * @return the value of t_green_sp_spmx.c_spms
     *
     * @mbggenerated
     */
    public String getcSpms() {
        return cSpms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_green_sp_spmx.c_spms
     *
     * @param cSpms the value for t_green_sp_spmx.c_spms
     *
     * @mbggenerated
     */
    public void setcSpms(String cSpms) {
        this.cSpms = cSpms == null ? null : cSpms.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_green_sp_spmx.n_spjg
     *
     * @return the value of t_green_sp_spmx.n_spjg
     *
     * @mbggenerated
     */
    public BigDecimal getnSpjg() {
        return nSpjg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_green_sp_spmx.n_spjg
     *
     * @param nSpjg the value for t_green_sp_spmx.n_spjg
     *
     * @mbggenerated
     */
    public void setnSpjg(BigDecimal nSpjg) {
        this.nSpjg = nSpjg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_green_sp_spmx.c_spdw
     *
     * @return the value of t_green_sp_spmx.c_spdw
     *
     * @mbggenerated
     */
    public String getcSpdw() {
        return cSpdw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_green_sp_spmx.c_spdw
     *
     * @param cSpdw the value for t_green_sp_spmx.c_spdw
     *
     * @mbggenerated
     */
    public void setcSpdw(String cSpdw) {
        this.cSpdw = cSpdw == null ? null : cSpdw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_green_sp_spmx.c_bz
     *
     * @return the value of t_green_sp_spmx.c_bz
     *
     * @mbggenerated
     */
    public String getcBz() {
        return cBz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_green_sp_spmx.c_bz
     *
     * @param cBz the value for t_green_sp_spmx.c_bz
     *
     * @mbggenerated
     */
    public void setcBz(String cBz) {
        this.cBz = cBz == null ? null : cBz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_green_sp_spmx.c_zt
     *
     * @return the value of t_green_sp_spmx.c_zt
     *
     * @mbggenerated
     */
    public String getcZt() {
        return cZt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_green_sp_spmx.c_zt
     *
     * @param cZt the value for t_green_sp_spmx.c_zt
     *
     * @mbggenerated
     */
    public void setcZt(String cZt) {
        this.cZt = cZt == null ? null : cZt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_green_sp_spmx.c_cjuser
     *
     * @return the value of t_green_sp_spmx.c_cjuser
     *
     * @mbggenerated
     */
    public String getcCjuser() {
        return cCjuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_green_sp_spmx.c_cjuser
     *
     * @param cCjuser the value for t_green_sp_spmx.c_cjuser
     *
     * @mbggenerated
     */
    public void setcCjuser(String cCjuser) {
        this.cCjuser = cCjuser == null ? null : cCjuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_green_sp_spmx.d_cjsj
     *
     * @return the value of t_green_sp_spmx.d_cjsj
     *
     * @mbggenerated
     */
    public Date getdCjsj() {
        return dCjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_green_sp_spmx.d_cjsj
     *
     * @param dCjsj the value for t_green_sp_spmx.d_cjsj
     *
     * @mbggenerated
     */
    public void setdCjsj(Date dCjsj) {
        this.dCjsj = dCjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_green_sp_spmx.c_xguser
     *
     * @return the value of t_green_sp_spmx.c_xguser
     *
     * @mbggenerated
     */
    public String getcXguser() {
        return cXguser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_green_sp_spmx.c_xguser
     *
     * @param cXguser the value for t_green_sp_spmx.c_xguser
     *
     * @mbggenerated
     */
    public void setcXguser(String cXguser) {
        this.cXguser = cXguser == null ? null : cXguser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_green_sp_spmx.d_xgsj
     *
     * @return the value of t_green_sp_spmx.d_xgsj
     *
     * @mbggenerated
     */
    public Date getdXgsj() {
        return dXgsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_green_sp_spmx.d_xgsj
     *
     * @param dXgsj the value for t_green_sp_spmx.d_xgsj
     *
     * @mbggenerated
     */
    public void setdXgsj(Date dXgsj) {
        this.dXgsj = dXgsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_sp_spmx
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", cSpbh=").append(cSpbh);
        sb.append(", cSpmc=").append(cSpmc);
        sb.append(", cSpms=").append(cSpms);
        sb.append(", nSpjg=").append(nSpjg);
        sb.append(", cSpdw=").append(cSpdw);
        sb.append(", cBz=").append(cBz);
        sb.append(", cZt=").append(cZt);
        sb.append(", cCjuser=").append(cCjuser);
        sb.append(", dCjsj=").append(dCjsj);
        sb.append(", cXguser=").append(cXguser);
        sb.append(", dXgsj=").append(dXgsj);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}