package com.greenplatform.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TGreenNlTxjlExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_green_nl_txjl
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_green_nl_txjl
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_green_nl_txjl
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_nl_txjl
     *
     * @mbggenerated
     */
    public TGreenNlTxjlExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_nl_txjl
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_nl_txjl
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_nl_txjl
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_nl_txjl
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_nl_txjl
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_nl_txjl
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_nl_txjl
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_nl_txjl
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_nl_txjl
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_nl_txjl
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_green_nl_txjl
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCLshIsNull() {
            addCriterion("c_lsh is null");
            return (Criteria) this;
        }

        public Criteria andCLshIsNotNull() {
            addCriterion("c_lsh is not null");
            return (Criteria) this;
        }

        public Criteria andCLshEqualTo(String value) {
            addCriterion("c_lsh =", value, "cLsh");
            return (Criteria) this;
        }

        public Criteria andCLshNotEqualTo(String value) {
            addCriterion("c_lsh <>", value, "cLsh");
            return (Criteria) this;
        }

        public Criteria andCLshGreaterThan(String value) {
            addCriterion("c_lsh >", value, "cLsh");
            return (Criteria) this;
        }

        public Criteria andCLshGreaterThanOrEqualTo(String value) {
            addCriterion("c_lsh >=", value, "cLsh");
            return (Criteria) this;
        }

        public Criteria andCLshLessThan(String value) {
            addCriterion("c_lsh <", value, "cLsh");
            return (Criteria) this;
        }

        public Criteria andCLshLessThanOrEqualTo(String value) {
            addCriterion("c_lsh <=", value, "cLsh");
            return (Criteria) this;
        }

        public Criteria andCLshLike(String value) {
            addCriterion("c_lsh like", value, "cLsh");
            return (Criteria) this;
        }

        public Criteria andCLshNotLike(String value) {
            addCriterion("c_lsh not like", value, "cLsh");
            return (Criteria) this;
        }

        public Criteria andCLshIn(List<String> values) {
            addCriterion("c_lsh in", values, "cLsh");
            return (Criteria) this;
        }

        public Criteria andCLshNotIn(List<String> values) {
            addCriterion("c_lsh not in", values, "cLsh");
            return (Criteria) this;
        }

        public Criteria andCLshBetween(String value1, String value2) {
            addCriterion("c_lsh between", value1, value2, "cLsh");
            return (Criteria) this;
        }

        public Criteria andCLshNotBetween(String value1, String value2) {
            addCriterion("c_lsh not between", value1, value2, "cLsh");
            return (Criteria) this;
        }

        public Criteria andNTxjeIsNull() {
            addCriterion("n_txje is null");
            return (Criteria) this;
        }

        public Criteria andNTxjeIsNotNull() {
            addCriterion("n_txje is not null");
            return (Criteria) this;
        }

        public Criteria andNTxjeEqualTo(BigDecimal value) {
            addCriterion("n_txje =", value, "nTxje");
            return (Criteria) this;
        }

        public Criteria andNTxjeNotEqualTo(BigDecimal value) {
            addCriterion("n_txje <>", value, "nTxje");
            return (Criteria) this;
        }

        public Criteria andNTxjeGreaterThan(BigDecimal value) {
            addCriterion("n_txje >", value, "nTxje");
            return (Criteria) this;
        }

        public Criteria andNTxjeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("n_txje >=", value, "nTxje");
            return (Criteria) this;
        }

        public Criteria andNTxjeLessThan(BigDecimal value) {
            addCriterion("n_txje <", value, "nTxje");
            return (Criteria) this;
        }

        public Criteria andNTxjeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("n_txje <=", value, "nTxje");
            return (Criteria) this;
        }

        public Criteria andNTxjeIn(List<BigDecimal> values) {
            addCriterion("n_txje in", values, "nTxje");
            return (Criteria) this;
        }

        public Criteria andNTxjeNotIn(List<BigDecimal> values) {
            addCriterion("n_txje not in", values, "nTxje");
            return (Criteria) this;
        }

        public Criteria andNTxjeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("n_txje between", value1, value2, "nTxje");
            return (Criteria) this;
        }

        public Criteria andNTxjeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("n_txje not between", value1, value2, "nTxje");
            return (Criteria) this;
        }

        public Criteria andNTxnlIsNull() {
            addCriterion("n_txnl is null");
            return (Criteria) this;
        }

        public Criteria andNTxnlIsNotNull() {
            addCriterion("n_txnl is not null");
            return (Criteria) this;
        }

        public Criteria andNTxnlEqualTo(BigDecimal value) {
            addCriterion("n_txnl =", value, "nTxnl");
            return (Criteria) this;
        }

        public Criteria andNTxnlNotEqualTo(BigDecimal value) {
            addCriterion("n_txnl <>", value, "nTxnl");
            return (Criteria) this;
        }

        public Criteria andNTxnlGreaterThan(BigDecimal value) {
            addCriterion("n_txnl >", value, "nTxnl");
            return (Criteria) this;
        }

        public Criteria andNTxnlGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("n_txnl >=", value, "nTxnl");
            return (Criteria) this;
        }

        public Criteria andNTxnlLessThan(BigDecimal value) {
            addCriterion("n_txnl <", value, "nTxnl");
            return (Criteria) this;
        }

        public Criteria andNTxnlLessThanOrEqualTo(BigDecimal value) {
            addCriterion("n_txnl <=", value, "nTxnl");
            return (Criteria) this;
        }

        public Criteria andNTxnlIn(List<BigDecimal> values) {
            addCriterion("n_txnl in", values, "nTxnl");
            return (Criteria) this;
        }

        public Criteria andNTxnlNotIn(List<BigDecimal> values) {
            addCriterion("n_txnl not in", values, "nTxnl");
            return (Criteria) this;
        }

        public Criteria andNTxnlBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("n_txnl between", value1, value2, "nTxnl");
            return (Criteria) this;
        }

        public Criteria andNTxnlNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("n_txnl not between", value1, value2, "nTxnl");
            return (Criteria) this;
        }

        public Criteria andDTxsjIsNull() {
            addCriterion("d_txsj is null");
            return (Criteria) this;
        }

        public Criteria andDTxsjIsNotNull() {
            addCriterion("d_txsj is not null");
            return (Criteria) this;
        }

        public Criteria andDTxsjEqualTo(Date value) {
            addCriterion("d_txsj =", value, "dTxsj");
            return (Criteria) this;
        }

        public Criteria andDTxsjNotEqualTo(Date value) {
            addCriterion("d_txsj <>", value, "dTxsj");
            return (Criteria) this;
        }

        public Criteria andDTxsjGreaterThan(Date value) {
            addCriterion("d_txsj >", value, "dTxsj");
            return (Criteria) this;
        }

        public Criteria andDTxsjGreaterThanOrEqualTo(Date value) {
            addCriterion("d_txsj >=", value, "dTxsj");
            return (Criteria) this;
        }

        public Criteria andDTxsjLessThan(Date value) {
            addCriterion("d_txsj <", value, "dTxsj");
            return (Criteria) this;
        }

        public Criteria andDTxsjLessThanOrEqualTo(Date value) {
            addCriterion("d_txsj <=", value, "dTxsj");
            return (Criteria) this;
        }

        public Criteria andDTxsjIn(List<Date> values) {
            addCriterion("d_txsj in", values, "dTxsj");
            return (Criteria) this;
        }

        public Criteria andDTxsjNotIn(List<Date> values) {
            addCriterion("d_txsj not in", values, "dTxsj");
            return (Criteria) this;
        }

        public Criteria andDTxsjBetween(Date value1, Date value2) {
            addCriterion("d_txsj between", value1, value2, "dTxsj");
            return (Criteria) this;
        }

        public Criteria andDTxsjNotBetween(Date value1, Date value2) {
            addCriterion("d_txsj not between", value1, value2, "dTxsj");
            return (Criteria) this;
        }

        public Criteria andCSfcgIsNull() {
            addCriterion("c_sfcg is null");
            return (Criteria) this;
        }

        public Criteria andCSfcgIsNotNull() {
            addCriterion("c_sfcg is not null");
            return (Criteria) this;
        }

        public Criteria andCSfcgEqualTo(String value) {
            addCriterion("c_sfcg =", value, "cSfcg");
            return (Criteria) this;
        }

        public Criteria andCSfcgNotEqualTo(String value) {
            addCriterion("c_sfcg <>", value, "cSfcg");
            return (Criteria) this;
        }

        public Criteria andCSfcgGreaterThan(String value) {
            addCriterion("c_sfcg >", value, "cSfcg");
            return (Criteria) this;
        }

        public Criteria andCSfcgGreaterThanOrEqualTo(String value) {
            addCriterion("c_sfcg >=", value, "cSfcg");
            return (Criteria) this;
        }

        public Criteria andCSfcgLessThan(String value) {
            addCriterion("c_sfcg <", value, "cSfcg");
            return (Criteria) this;
        }

        public Criteria andCSfcgLessThanOrEqualTo(String value) {
            addCriterion("c_sfcg <=", value, "cSfcg");
            return (Criteria) this;
        }

        public Criteria andCSfcgLike(String value) {
            addCriterion("c_sfcg like", value, "cSfcg");
            return (Criteria) this;
        }

        public Criteria andCSfcgNotLike(String value) {
            addCriterion("c_sfcg not like", value, "cSfcg");
            return (Criteria) this;
        }

        public Criteria andCSfcgIn(List<String> values) {
            addCriterion("c_sfcg in", values, "cSfcg");
            return (Criteria) this;
        }

        public Criteria andCSfcgNotIn(List<String> values) {
            addCriterion("c_sfcg not in", values, "cSfcg");
            return (Criteria) this;
        }

        public Criteria andCSfcgBetween(String value1, String value2) {
            addCriterion("c_sfcg between", value1, value2, "cSfcg");
            return (Criteria) this;
        }

        public Criteria andCSfcgNotBetween(String value1, String value2) {
            addCriterion("c_sfcg not between", value1, value2, "cSfcg");
            return (Criteria) this;
        }

        public Criteria andCTxfsIsNull() {
            addCriterion("c_txfs is null");
            return (Criteria) this;
        }

        public Criteria andCTxfsIsNotNull() {
            addCriterion("c_txfs is not null");
            return (Criteria) this;
        }

        public Criteria andCTxfsEqualTo(String value) {
            addCriterion("c_txfs =", value, "cTxfs");
            return (Criteria) this;
        }

        public Criteria andCTxfsNotEqualTo(String value) {
            addCriterion("c_txfs <>", value, "cTxfs");
            return (Criteria) this;
        }

        public Criteria andCTxfsGreaterThan(String value) {
            addCriterion("c_txfs >", value, "cTxfs");
            return (Criteria) this;
        }

        public Criteria andCTxfsGreaterThanOrEqualTo(String value) {
            addCriterion("c_txfs >=", value, "cTxfs");
            return (Criteria) this;
        }

        public Criteria andCTxfsLessThan(String value) {
            addCriterion("c_txfs <", value, "cTxfs");
            return (Criteria) this;
        }

        public Criteria andCTxfsLessThanOrEqualTo(String value) {
            addCriterion("c_txfs <=", value, "cTxfs");
            return (Criteria) this;
        }

        public Criteria andCTxfsLike(String value) {
            addCriterion("c_txfs like", value, "cTxfs");
            return (Criteria) this;
        }

        public Criteria andCTxfsNotLike(String value) {
            addCriterion("c_txfs not like", value, "cTxfs");
            return (Criteria) this;
        }

        public Criteria andCTxfsIn(List<String> values) {
            addCriterion("c_txfs in", values, "cTxfs");
            return (Criteria) this;
        }

        public Criteria andCTxfsNotIn(List<String> values) {
            addCriterion("c_txfs not in", values, "cTxfs");
            return (Criteria) this;
        }

        public Criteria andCTxfsBetween(String value1, String value2) {
            addCriterion("c_txfs between", value1, value2, "cTxfs");
            return (Criteria) this;
        }

        public Criteria andCTxfsNotBetween(String value1, String value2) {
            addCriterion("c_txfs not between", value1, value2, "cTxfs");
            return (Criteria) this;
        }

        public Criteria andCTxzhIsNull() {
            addCriterion("c_txzh is null");
            return (Criteria) this;
        }

        public Criteria andCTxzhIsNotNull() {
            addCriterion("c_txzh is not null");
            return (Criteria) this;
        }

        public Criteria andCTxzhEqualTo(String value) {
            addCriterion("c_txzh =", value, "cTxzh");
            return (Criteria) this;
        }

        public Criteria andCTxzhNotEqualTo(String value) {
            addCriterion("c_txzh <>", value, "cTxzh");
            return (Criteria) this;
        }

        public Criteria andCTxzhGreaterThan(String value) {
            addCriterion("c_txzh >", value, "cTxzh");
            return (Criteria) this;
        }

        public Criteria andCTxzhGreaterThanOrEqualTo(String value) {
            addCriterion("c_txzh >=", value, "cTxzh");
            return (Criteria) this;
        }

        public Criteria andCTxzhLessThan(String value) {
            addCriterion("c_txzh <", value, "cTxzh");
            return (Criteria) this;
        }

        public Criteria andCTxzhLessThanOrEqualTo(String value) {
            addCriterion("c_txzh <=", value, "cTxzh");
            return (Criteria) this;
        }

        public Criteria andCTxzhLike(String value) {
            addCriterion("c_txzh like", value, "cTxzh");
            return (Criteria) this;
        }

        public Criteria andCTxzhNotLike(String value) {
            addCriterion("c_txzh not like", value, "cTxzh");
            return (Criteria) this;
        }

        public Criteria andCTxzhIn(List<String> values) {
            addCriterion("c_txzh in", values, "cTxzh");
            return (Criteria) this;
        }

        public Criteria andCTxzhNotIn(List<String> values) {
            addCriterion("c_txzh not in", values, "cTxzh");
            return (Criteria) this;
        }

        public Criteria andCTxzhBetween(String value1, String value2) {
            addCriterion("c_txzh between", value1, value2, "cTxzh");
            return (Criteria) this;
        }

        public Criteria andCTxzhNotBetween(String value1, String value2) {
            addCriterion("c_txzh not between", value1, value2, "cTxzh");
            return (Criteria) this;
        }

        public Criteria andCFkzhIsNull() {
            addCriterion("c_fkzh is null");
            return (Criteria) this;
        }

        public Criteria andCFkzhIsNotNull() {
            addCriterion("c_fkzh is not null");
            return (Criteria) this;
        }

        public Criteria andCFkzhEqualTo(String value) {
            addCriterion("c_fkzh =", value, "cFkzh");
            return (Criteria) this;
        }

        public Criteria andCFkzhNotEqualTo(String value) {
            addCriterion("c_fkzh <>", value, "cFkzh");
            return (Criteria) this;
        }

        public Criteria andCFkzhGreaterThan(String value) {
            addCriterion("c_fkzh >", value, "cFkzh");
            return (Criteria) this;
        }

        public Criteria andCFkzhGreaterThanOrEqualTo(String value) {
            addCriterion("c_fkzh >=", value, "cFkzh");
            return (Criteria) this;
        }

        public Criteria andCFkzhLessThan(String value) {
            addCriterion("c_fkzh <", value, "cFkzh");
            return (Criteria) this;
        }

        public Criteria andCFkzhLessThanOrEqualTo(String value) {
            addCriterion("c_fkzh <=", value, "cFkzh");
            return (Criteria) this;
        }

        public Criteria andCFkzhLike(String value) {
            addCriterion("c_fkzh like", value, "cFkzh");
            return (Criteria) this;
        }

        public Criteria andCFkzhNotLike(String value) {
            addCriterion("c_fkzh not like", value, "cFkzh");
            return (Criteria) this;
        }

        public Criteria andCFkzhIn(List<String> values) {
            addCriterion("c_fkzh in", values, "cFkzh");
            return (Criteria) this;
        }

        public Criteria andCFkzhNotIn(List<String> values) {
            addCriterion("c_fkzh not in", values, "cFkzh");
            return (Criteria) this;
        }

        public Criteria andCFkzhBetween(String value1, String value2) {
            addCriterion("c_fkzh between", value1, value2, "cFkzh");
            return (Criteria) this;
        }

        public Criteria andCFkzhNotBetween(String value1, String value2) {
            addCriterion("c_fkzh not between", value1, value2, "cFkzh");
            return (Criteria) this;
        }

        public Criteria andCBzIsNull() {
            addCriterion("c_bz is null");
            return (Criteria) this;
        }

        public Criteria andCBzIsNotNull() {
            addCriterion("c_bz is not null");
            return (Criteria) this;
        }

        public Criteria andCBzEqualTo(String value) {
            addCriterion("c_bz =", value, "cBz");
            return (Criteria) this;
        }

        public Criteria andCBzNotEqualTo(String value) {
            addCriterion("c_bz <>", value, "cBz");
            return (Criteria) this;
        }

        public Criteria andCBzGreaterThan(String value) {
            addCriterion("c_bz >", value, "cBz");
            return (Criteria) this;
        }

        public Criteria andCBzGreaterThanOrEqualTo(String value) {
            addCriterion("c_bz >=", value, "cBz");
            return (Criteria) this;
        }

        public Criteria andCBzLessThan(String value) {
            addCriterion("c_bz <", value, "cBz");
            return (Criteria) this;
        }

        public Criteria andCBzLessThanOrEqualTo(String value) {
            addCriterion("c_bz <=", value, "cBz");
            return (Criteria) this;
        }

        public Criteria andCBzLike(String value) {
            addCriterion("c_bz like", value, "cBz");
            return (Criteria) this;
        }

        public Criteria andCBzNotLike(String value) {
            addCriterion("c_bz not like", value, "cBz");
            return (Criteria) this;
        }

        public Criteria andCBzIn(List<String> values) {
            addCriterion("c_bz in", values, "cBz");
            return (Criteria) this;
        }

        public Criteria andCBzNotIn(List<String> values) {
            addCriterion("c_bz not in", values, "cBz");
            return (Criteria) this;
        }

        public Criteria andCBzBetween(String value1, String value2) {
            addCriterion("c_bz between", value1, value2, "cBz");
            return (Criteria) this;
        }

        public Criteria andCBzNotBetween(String value1, String value2) {
            addCriterion("c_bz not between", value1, value2, "cBz");
            return (Criteria) this;
        }

        public Criteria andCZtIsNull() {
            addCriterion("c_zt is null");
            return (Criteria) this;
        }

        public Criteria andCZtIsNotNull() {
            addCriterion("c_zt is not null");
            return (Criteria) this;
        }

        public Criteria andCZtEqualTo(String value) {
            addCriterion("c_zt =", value, "cZt");
            return (Criteria) this;
        }

        public Criteria andCZtNotEqualTo(String value) {
            addCriterion("c_zt <>", value, "cZt");
            return (Criteria) this;
        }

        public Criteria andCZtGreaterThan(String value) {
            addCriterion("c_zt >", value, "cZt");
            return (Criteria) this;
        }

        public Criteria andCZtGreaterThanOrEqualTo(String value) {
            addCriterion("c_zt >=", value, "cZt");
            return (Criteria) this;
        }

        public Criteria andCZtLessThan(String value) {
            addCriterion("c_zt <", value, "cZt");
            return (Criteria) this;
        }

        public Criteria andCZtLessThanOrEqualTo(String value) {
            addCriterion("c_zt <=", value, "cZt");
            return (Criteria) this;
        }

        public Criteria andCZtLike(String value) {
            addCriterion("c_zt like", value, "cZt");
            return (Criteria) this;
        }

        public Criteria andCZtNotLike(String value) {
            addCriterion("c_zt not like", value, "cZt");
            return (Criteria) this;
        }

        public Criteria andCZtIn(List<String> values) {
            addCriterion("c_zt in", values, "cZt");
            return (Criteria) this;
        }

        public Criteria andCZtNotIn(List<String> values) {
            addCriterion("c_zt not in", values, "cZt");
            return (Criteria) this;
        }

        public Criteria andCZtBetween(String value1, String value2) {
            addCriterion("c_zt between", value1, value2, "cZt");
            return (Criteria) this;
        }

        public Criteria andCZtNotBetween(String value1, String value2) {
            addCriterion("c_zt not between", value1, value2, "cZt");
            return (Criteria) this;
        }

        public Criteria andCCjuserIsNull() {
            addCriterion("c_cjuser is null");
            return (Criteria) this;
        }

        public Criteria andCCjuserIsNotNull() {
            addCriterion("c_cjuser is not null");
            return (Criteria) this;
        }

        public Criteria andCCjuserEqualTo(String value) {
            addCriterion("c_cjuser =", value, "cCjuser");
            return (Criteria) this;
        }

        public Criteria andCCjuserNotEqualTo(String value) {
            addCriterion("c_cjuser <>", value, "cCjuser");
            return (Criteria) this;
        }

        public Criteria andCCjuserGreaterThan(String value) {
            addCriterion("c_cjuser >", value, "cCjuser");
            return (Criteria) this;
        }

        public Criteria andCCjuserGreaterThanOrEqualTo(String value) {
            addCriterion("c_cjuser >=", value, "cCjuser");
            return (Criteria) this;
        }

        public Criteria andCCjuserLessThan(String value) {
            addCriterion("c_cjuser <", value, "cCjuser");
            return (Criteria) this;
        }

        public Criteria andCCjuserLessThanOrEqualTo(String value) {
            addCriterion("c_cjuser <=", value, "cCjuser");
            return (Criteria) this;
        }

        public Criteria andCCjuserLike(String value) {
            addCriterion("c_cjuser like", value, "cCjuser");
            return (Criteria) this;
        }

        public Criteria andCCjuserNotLike(String value) {
            addCriterion("c_cjuser not like", value, "cCjuser");
            return (Criteria) this;
        }

        public Criteria andCCjuserIn(List<String> values) {
            addCriterion("c_cjuser in", values, "cCjuser");
            return (Criteria) this;
        }

        public Criteria andCCjuserNotIn(List<String> values) {
            addCriterion("c_cjuser not in", values, "cCjuser");
            return (Criteria) this;
        }

        public Criteria andCCjuserBetween(String value1, String value2) {
            addCriterion("c_cjuser between", value1, value2, "cCjuser");
            return (Criteria) this;
        }

        public Criteria andCCjuserNotBetween(String value1, String value2) {
            addCriterion("c_cjuser not between", value1, value2, "cCjuser");
            return (Criteria) this;
        }

        public Criteria andDCjsjIsNull() {
            addCriterion("d_cjsj is null");
            return (Criteria) this;
        }

        public Criteria andDCjsjIsNotNull() {
            addCriterion("d_cjsj is not null");
            return (Criteria) this;
        }

        public Criteria andDCjsjEqualTo(Date value) {
            addCriterion("d_cjsj =", value, "dCjsj");
            return (Criteria) this;
        }

        public Criteria andDCjsjNotEqualTo(Date value) {
            addCriterion("d_cjsj <>", value, "dCjsj");
            return (Criteria) this;
        }

        public Criteria andDCjsjGreaterThan(Date value) {
            addCriterion("d_cjsj >", value, "dCjsj");
            return (Criteria) this;
        }

        public Criteria andDCjsjGreaterThanOrEqualTo(Date value) {
            addCriterion("d_cjsj >=", value, "dCjsj");
            return (Criteria) this;
        }

        public Criteria andDCjsjLessThan(Date value) {
            addCriterion("d_cjsj <", value, "dCjsj");
            return (Criteria) this;
        }

        public Criteria andDCjsjLessThanOrEqualTo(Date value) {
            addCriterion("d_cjsj <=", value, "dCjsj");
            return (Criteria) this;
        }

        public Criteria andDCjsjIn(List<Date> values) {
            addCriterion("d_cjsj in", values, "dCjsj");
            return (Criteria) this;
        }

        public Criteria andDCjsjNotIn(List<Date> values) {
            addCriterion("d_cjsj not in", values, "dCjsj");
            return (Criteria) this;
        }

        public Criteria andDCjsjBetween(Date value1, Date value2) {
            addCriterion("d_cjsj between", value1, value2, "dCjsj");
            return (Criteria) this;
        }

        public Criteria andDCjsjNotBetween(Date value1, Date value2) {
            addCriterion("d_cjsj not between", value1, value2, "dCjsj");
            return (Criteria) this;
        }

        public Criteria andCXguserIsNull() {
            addCriterion("c_xguser is null");
            return (Criteria) this;
        }

        public Criteria andCXguserIsNotNull() {
            addCriterion("c_xguser is not null");
            return (Criteria) this;
        }

        public Criteria andCXguserEqualTo(String value) {
            addCriterion("c_xguser =", value, "cXguser");
            return (Criteria) this;
        }

        public Criteria andCXguserNotEqualTo(String value) {
            addCriterion("c_xguser <>", value, "cXguser");
            return (Criteria) this;
        }

        public Criteria andCXguserGreaterThan(String value) {
            addCriterion("c_xguser >", value, "cXguser");
            return (Criteria) this;
        }

        public Criteria andCXguserGreaterThanOrEqualTo(String value) {
            addCriterion("c_xguser >=", value, "cXguser");
            return (Criteria) this;
        }

        public Criteria andCXguserLessThan(String value) {
            addCriterion("c_xguser <", value, "cXguser");
            return (Criteria) this;
        }

        public Criteria andCXguserLessThanOrEqualTo(String value) {
            addCriterion("c_xguser <=", value, "cXguser");
            return (Criteria) this;
        }

        public Criteria andCXguserLike(String value) {
            addCriterion("c_xguser like", value, "cXguser");
            return (Criteria) this;
        }

        public Criteria andCXguserNotLike(String value) {
            addCriterion("c_xguser not like", value, "cXguser");
            return (Criteria) this;
        }

        public Criteria andCXguserIn(List<String> values) {
            addCriterion("c_xguser in", values, "cXguser");
            return (Criteria) this;
        }

        public Criteria andCXguserNotIn(List<String> values) {
            addCriterion("c_xguser not in", values, "cXguser");
            return (Criteria) this;
        }

        public Criteria andCXguserBetween(String value1, String value2) {
            addCriterion("c_xguser between", value1, value2, "cXguser");
            return (Criteria) this;
        }

        public Criteria andCXguserNotBetween(String value1, String value2) {
            addCriterion("c_xguser not between", value1, value2, "cXguser");
            return (Criteria) this;
        }

        public Criteria andDXgsjIsNull() {
            addCriterion("d_xgsj is null");
            return (Criteria) this;
        }

        public Criteria andDXgsjIsNotNull() {
            addCriterion("d_xgsj is not null");
            return (Criteria) this;
        }

        public Criteria andDXgsjEqualTo(Date value) {
            addCriterion("d_xgsj =", value, "dXgsj");
            return (Criteria) this;
        }

        public Criteria andDXgsjNotEqualTo(Date value) {
            addCriterion("d_xgsj <>", value, "dXgsj");
            return (Criteria) this;
        }

        public Criteria andDXgsjGreaterThan(Date value) {
            addCriterion("d_xgsj >", value, "dXgsj");
            return (Criteria) this;
        }

        public Criteria andDXgsjGreaterThanOrEqualTo(Date value) {
            addCriterion("d_xgsj >=", value, "dXgsj");
            return (Criteria) this;
        }

        public Criteria andDXgsjLessThan(Date value) {
            addCriterion("d_xgsj <", value, "dXgsj");
            return (Criteria) this;
        }

        public Criteria andDXgsjLessThanOrEqualTo(Date value) {
            addCriterion("d_xgsj <=", value, "dXgsj");
            return (Criteria) this;
        }

        public Criteria andDXgsjIn(List<Date> values) {
            addCriterion("d_xgsj in", values, "dXgsj");
            return (Criteria) this;
        }

        public Criteria andDXgsjNotIn(List<Date> values) {
            addCriterion("d_xgsj not in", values, "dXgsj");
            return (Criteria) this;
        }

        public Criteria andDXgsjBetween(Date value1, Date value2) {
            addCriterion("d_xgsj between", value1, value2, "dXgsj");
            return (Criteria) this;
        }

        public Criteria andDXgsjNotBetween(Date value1, Date value2) {
            addCriterion("d_xgsj not between", value1, value2, "dXgsj");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_green_nl_txjl
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_green_nl_txjl
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}