package com.greenplatform.model;

import java.io.Serializable;
import java.util.Date;

public class TGreenNlCzjl implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_green_nl_czjl.c_lsh
     *
     * @mbggenerated
     */
    private String cLsh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_green_nl_czjl.c_czje
     *
     * @mbggenerated
     */
    private String cCzje;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_green_nl_czjl.c_cznl
     *
     * @mbggenerated
     */
    private String cCznl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_green_nl_czjl.d_czsj
     *
     * @mbggenerated
     */
    private Date dCzsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_green_nl_czjl.c_sfcg
     *
     * @mbggenerated
     */
    private String cSfcg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_green_nl_czjl.c_czfs
     *
     * @mbggenerated
     */
    private String cCzfs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_green_nl_czjl.c_czzh
     *
     * @mbggenerated
     */
    private String cCzzh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_green_nl_czjl.c_dzzh
     *
     * @mbggenerated
     */
    private String cDzzh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_green_nl_czjl.c_bz
     *
     * @mbggenerated
     */
    private String cBz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_green_nl_czjl.c_zt
     *
     * @mbggenerated
     */
    private String cZt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_green_nl_czjl.c_cjuser
     *
     * @mbggenerated
     */
    private String cCjuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_green_nl_czjl.d_cjsj
     *
     * @mbggenerated
     */
    private Date dCjsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_green_nl_czjl.c_xguser
     *
     * @mbggenerated
     */
    private String cXguser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_green_nl_czjl.d_xgsj
     *
     * @mbggenerated
     */
    private Date dXgsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_green_nl_czjl
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_green_nl_czjl.c_lsh
     *
     * @return the value of t_green_nl_czjl.c_lsh
     *
     * @mbggenerated
     */
    public String getcLsh() {
        return cLsh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_green_nl_czjl.c_lsh
     *
     * @param cLsh the value for t_green_nl_czjl.c_lsh
     *
     * @mbggenerated
     */
    public void setcLsh(String cLsh) {
        this.cLsh = cLsh == null ? null : cLsh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_green_nl_czjl.c_czje
     *
     * @return the value of t_green_nl_czjl.c_czje
     *
     * @mbggenerated
     */
    public String getcCzje() {
        return cCzje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_green_nl_czjl.c_czje
     *
     * @param cCzje the value for t_green_nl_czjl.c_czje
     *
     * @mbggenerated
     */
    public void setcCzje(String cCzje) {
        this.cCzje = cCzje == null ? null : cCzje.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_green_nl_czjl.c_cznl
     *
     * @return the value of t_green_nl_czjl.c_cznl
     *
     * @mbggenerated
     */
    public String getcCznl() {
        return cCznl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_green_nl_czjl.c_cznl
     *
     * @param cCznl the value for t_green_nl_czjl.c_cznl
     *
     * @mbggenerated
     */
    public void setcCznl(String cCznl) {
        this.cCznl = cCznl == null ? null : cCznl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_green_nl_czjl.d_czsj
     *
     * @return the value of t_green_nl_czjl.d_czsj
     *
     * @mbggenerated
     */
    public Date getdCzsj() {
        return dCzsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_green_nl_czjl.d_czsj
     *
     * @param dCzsj the value for t_green_nl_czjl.d_czsj
     *
     * @mbggenerated
     */
    public void setdCzsj(Date dCzsj) {
        this.dCzsj = dCzsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_green_nl_czjl.c_sfcg
     *
     * @return the value of t_green_nl_czjl.c_sfcg
     *
     * @mbggenerated
     */
    public String getcSfcg() {
        return cSfcg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_green_nl_czjl.c_sfcg
     *
     * @param cSfcg the value for t_green_nl_czjl.c_sfcg
     *
     * @mbggenerated
     */
    public void setcSfcg(String cSfcg) {
        this.cSfcg = cSfcg == null ? null : cSfcg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_green_nl_czjl.c_czfs
     *
     * @return the value of t_green_nl_czjl.c_czfs
     *
     * @mbggenerated
     */
    public String getcCzfs() {
        return cCzfs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_green_nl_czjl.c_czfs
     *
     * @param cCzfs the value for t_green_nl_czjl.c_czfs
     *
     * @mbggenerated
     */
    public void setcCzfs(String cCzfs) {
        this.cCzfs = cCzfs == null ? null : cCzfs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_green_nl_czjl.c_czzh
     *
     * @return the value of t_green_nl_czjl.c_czzh
     *
     * @mbggenerated
     */
    public String getcCzzh() {
        return cCzzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_green_nl_czjl.c_czzh
     *
     * @param cCzzh the value for t_green_nl_czjl.c_czzh
     *
     * @mbggenerated
     */
    public void setcCzzh(String cCzzh) {
        this.cCzzh = cCzzh == null ? null : cCzzh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_green_nl_czjl.c_dzzh
     *
     * @return the value of t_green_nl_czjl.c_dzzh
     *
     * @mbggenerated
     */
    public String getcDzzh() {
        return cDzzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_green_nl_czjl.c_dzzh
     *
     * @param cDzzh the value for t_green_nl_czjl.c_dzzh
     *
     * @mbggenerated
     */
    public void setcDzzh(String cDzzh) {
        this.cDzzh = cDzzh == null ? null : cDzzh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_green_nl_czjl.c_bz
     *
     * @return the value of t_green_nl_czjl.c_bz
     *
     * @mbggenerated
     */
    public String getcBz() {
        return cBz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_green_nl_czjl.c_bz
     *
     * @param cBz the value for t_green_nl_czjl.c_bz
     *
     * @mbggenerated
     */
    public void setcBz(String cBz) {
        this.cBz = cBz == null ? null : cBz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_green_nl_czjl.c_zt
     *
     * @return the value of t_green_nl_czjl.c_zt
     *
     * @mbggenerated
     */
    public String getcZt() {
        return cZt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_green_nl_czjl.c_zt
     *
     * @param cZt the value for t_green_nl_czjl.c_zt
     *
     * @mbggenerated
     */
    public void setcZt(String cZt) {
        this.cZt = cZt == null ? null : cZt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_green_nl_czjl.c_cjuser
     *
     * @return the value of t_green_nl_czjl.c_cjuser
     *
     * @mbggenerated
     */
    public String getcCjuser() {
        return cCjuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_green_nl_czjl.c_cjuser
     *
     * @param cCjuser the value for t_green_nl_czjl.c_cjuser
     *
     * @mbggenerated
     */
    public void setcCjuser(String cCjuser) {
        this.cCjuser = cCjuser == null ? null : cCjuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_green_nl_czjl.d_cjsj
     *
     * @return the value of t_green_nl_czjl.d_cjsj
     *
     * @mbggenerated
     */
    public Date getdCjsj() {
        return dCjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_green_nl_czjl.d_cjsj
     *
     * @param dCjsj the value for t_green_nl_czjl.d_cjsj
     *
     * @mbggenerated
     */
    public void setdCjsj(Date dCjsj) {
        this.dCjsj = dCjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_green_nl_czjl.c_xguser
     *
     * @return the value of t_green_nl_czjl.c_xguser
     *
     * @mbggenerated
     */
    public String getcXguser() {
        return cXguser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_green_nl_czjl.c_xguser
     *
     * @param cXguser the value for t_green_nl_czjl.c_xguser
     *
     * @mbggenerated
     */
    public void setcXguser(String cXguser) {
        this.cXguser = cXguser == null ? null : cXguser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_green_nl_czjl.d_xgsj
     *
     * @return the value of t_green_nl_czjl.d_xgsj
     *
     * @mbggenerated
     */
    public Date getdXgsj() {
        return dXgsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_green_nl_czjl.d_xgsj
     *
     * @param dXgsj the value for t_green_nl_czjl.d_xgsj
     *
     * @mbggenerated
     */
    public void setdXgsj(Date dXgsj) {
        this.dXgsj = dXgsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_nl_czjl
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", cLsh=").append(cLsh);
        sb.append(", cCzje=").append(cCzje);
        sb.append(", cCznl=").append(cCznl);
        sb.append(", dCzsj=").append(dCzsj);
        sb.append(", cSfcg=").append(cSfcg);
        sb.append(", cCzfs=").append(cCzfs);
        sb.append(", cCzzh=").append(cCzzh);
        sb.append(", cDzzh=").append(cDzzh);
        sb.append(", cBz=").append(cBz);
        sb.append(", cZt=").append(cZt);
        sb.append(", cCjuser=").append(cCjuser);
        sb.append(", dCjsj=").append(dCjsj);
        sb.append(", cXguser=").append(cXguser);
        sb.append(", dXgsj=").append(dXgsj);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}