package com.greenplatform.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class TGreenNlTxjl implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_green_nl_txjl.c_lsh
     *
     * @mbggenerated
     */
    private String cLsh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_green_nl_txjl.c_dzzh
     *
     * @mbggenerated
     */
    private String cDzzh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_green_nl_txjl.c_fkzh
     *
     * @mbggenerated
     */
    private String cFkzh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_green_nl_txjl.n_txje
     *
     * @mbggenerated
     */
    private BigDecimal nTxje;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_green_nl_txjl.n_txnl
     *
     * @mbggenerated
     */
    private BigDecimal nTxnl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_green_nl_txjl.d_txsj
     *
     * @mbggenerated
     */
    private Date dTxsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_green_nl_txjl.d_dzsj
     *
     * @mbggenerated
     */
    private Date dDzsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_green_nl_txjl.c_sfcg
     *
     * @mbggenerated
     */
    private String cSfcg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_green_nl_txjl.c_txfs
     *
     * @mbggenerated
     */
    private String cTxfs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_green_nl_txjl.c_txyh
     *
     * @mbggenerated
     */
    private String cTxyh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_green_nl_txjl.c_txkh
     *
     * @mbggenerated
     */
    private String cTxkh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_green_nl_txjl.c_zzdh
     *
     * @mbggenerated
     */
    private String cZzdh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_green_nl_txjl.c_bz
     *
     * @mbggenerated
     */
    private String cBz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_green_nl_txjl.c_zt
     *
     * @mbggenerated
     */
    private String cZt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_green_nl_txjl.c_cjuser
     *
     * @mbggenerated
     */
    private String cCjuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_green_nl_txjl.d_cjsj
     *
     * @mbggenerated
     */
    private Date dCjsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_green_nl_txjl.c_xguser
     *
     * @mbggenerated
     */
    private String cXguser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_green_nl_txjl.d_xgsj
     *
     * @mbggenerated
     */
    private Date dXgsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_green_nl_txjl
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_green_nl_txjl.c_lsh
     *
     * @return the value of t_green_nl_txjl.c_lsh
     *
     * @mbggenerated
     */
    public String getcLsh() {
        return cLsh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_green_nl_txjl.c_lsh
     *
     * @param cLsh the value for t_green_nl_txjl.c_lsh
     *
     * @mbggenerated
     */
    public void setcLsh(String cLsh) {
        this.cLsh = cLsh == null ? null : cLsh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_green_nl_txjl.c_dzzh
     *
     * @return the value of t_green_nl_txjl.c_dzzh
     *
     * @mbggenerated
     */
    public String getcDzzh() {
        return cDzzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_green_nl_txjl.c_dzzh
     *
     * @param cDzzh the value for t_green_nl_txjl.c_dzzh
     *
     * @mbggenerated
     */
    public void setcDzzh(String cDzzh) {
        this.cDzzh = cDzzh == null ? null : cDzzh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_green_nl_txjl.c_fkzh
     *
     * @return the value of t_green_nl_txjl.c_fkzh
     *
     * @mbggenerated
     */
    public String getcFkzh() {
        return cFkzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_green_nl_txjl.c_fkzh
     *
     * @param cFkzh the value for t_green_nl_txjl.c_fkzh
     *
     * @mbggenerated
     */
    public void setcFkzh(String cFkzh) {
        this.cFkzh = cFkzh == null ? null : cFkzh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_green_nl_txjl.n_txje
     *
     * @return the value of t_green_nl_txjl.n_txje
     *
     * @mbggenerated
     */
    public BigDecimal getnTxje() {
        return nTxje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_green_nl_txjl.n_txje
     *
     * @param nTxje the value for t_green_nl_txjl.n_txje
     *
     * @mbggenerated
     */
    public void setnTxje(BigDecimal nTxje) {
        this.nTxje = nTxje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_green_nl_txjl.n_txnl
     *
     * @return the value of t_green_nl_txjl.n_txnl
     *
     * @mbggenerated
     */
    public BigDecimal getnTxnl() {
        return nTxnl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_green_nl_txjl.n_txnl
     *
     * @param nTxnl the value for t_green_nl_txjl.n_txnl
     *
     * @mbggenerated
     */
    public void setnTxnl(BigDecimal nTxnl) {
        this.nTxnl = nTxnl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_green_nl_txjl.d_txsj
     *
     * @return the value of t_green_nl_txjl.d_txsj
     *
     * @mbggenerated
     */
    public Date getdTxsj() {
        return dTxsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_green_nl_txjl.d_txsj
     *
     * @param dTxsj the value for t_green_nl_txjl.d_txsj
     *
     * @mbggenerated
     */
    public void setdTxsj(Date dTxsj) {
        this.dTxsj = dTxsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_green_nl_txjl.d_dzsj
     *
     * @return the value of t_green_nl_txjl.d_dzsj
     *
     * @mbggenerated
     */
    public Date getdDzsj() {
        return dDzsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_green_nl_txjl.d_dzsj
     *
     * @param dDzsj the value for t_green_nl_txjl.d_dzsj
     *
     * @mbggenerated
     */
    public void setdDzsj(Date dDzsj) {
        this.dDzsj = dDzsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_green_nl_txjl.c_sfcg
     *
     * @return the value of t_green_nl_txjl.c_sfcg
     *
     * @mbggenerated
     */
    public String getcSfcg() {
        return cSfcg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_green_nl_txjl.c_sfcg
     *
     * @param cSfcg the value for t_green_nl_txjl.c_sfcg
     *
     * @mbggenerated
     */
    public void setcSfcg(String cSfcg) {
        this.cSfcg = cSfcg == null ? null : cSfcg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_green_nl_txjl.c_txfs
     *
     * @return the value of t_green_nl_txjl.c_txfs
     *
     * @mbggenerated
     */
    public String getcTxfs() {
        return cTxfs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_green_nl_txjl.c_txfs
     *
     * @param cTxfs the value for t_green_nl_txjl.c_txfs
     *
     * @mbggenerated
     */
    public void setcTxfs(String cTxfs) {
        this.cTxfs = cTxfs == null ? null : cTxfs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_green_nl_txjl.c_txyh
     *
     * @return the value of t_green_nl_txjl.c_txyh
     *
     * @mbggenerated
     */
    public String getcTxyh() {
        return cTxyh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_green_nl_txjl.c_txyh
     *
     * @param cTxyh the value for t_green_nl_txjl.c_txyh
     *
     * @mbggenerated
     */
    public void setcTxyh(String cTxyh) {
        this.cTxyh = cTxyh == null ? null : cTxyh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_green_nl_txjl.c_txkh
     *
     * @return the value of t_green_nl_txjl.c_txkh
     *
     * @mbggenerated
     */
    public String getcTxkh() {
        return cTxkh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_green_nl_txjl.c_txkh
     *
     * @param cTxkh the value for t_green_nl_txjl.c_txkh
     *
     * @mbggenerated
     */
    public void setcTxkh(String cTxkh) {
        this.cTxkh = cTxkh == null ? null : cTxkh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_green_nl_txjl.c_zzdh
     *
     * @return the value of t_green_nl_txjl.c_zzdh
     *
     * @mbggenerated
     */
    public String getcZzdh() {
        return cZzdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_green_nl_txjl.c_zzdh
     *
     * @param cZzdh the value for t_green_nl_txjl.c_zzdh
     *
     * @mbggenerated
     */
    public void setcZzdh(String cZzdh) {
        this.cZzdh = cZzdh == null ? null : cZzdh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_green_nl_txjl.c_bz
     *
     * @return the value of t_green_nl_txjl.c_bz
     *
     * @mbggenerated
     */
    public String getcBz() {
        return cBz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_green_nl_txjl.c_bz
     *
     * @param cBz the value for t_green_nl_txjl.c_bz
     *
     * @mbggenerated
     */
    public void setcBz(String cBz) {
        this.cBz = cBz == null ? null : cBz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_green_nl_txjl.c_zt
     *
     * @return the value of t_green_nl_txjl.c_zt
     *
     * @mbggenerated
     */
    public String getcZt() {
        return cZt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_green_nl_txjl.c_zt
     *
     * @param cZt the value for t_green_nl_txjl.c_zt
     *
     * @mbggenerated
     */
    public void setcZt(String cZt) {
        this.cZt = cZt == null ? null : cZt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_green_nl_txjl.c_cjuser
     *
     * @return the value of t_green_nl_txjl.c_cjuser
     *
     * @mbggenerated
     */
    public String getcCjuser() {
        return cCjuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_green_nl_txjl.c_cjuser
     *
     * @param cCjuser the value for t_green_nl_txjl.c_cjuser
     *
     * @mbggenerated
     */
    public void setcCjuser(String cCjuser) {
        this.cCjuser = cCjuser == null ? null : cCjuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_green_nl_txjl.d_cjsj
     *
     * @return the value of t_green_nl_txjl.d_cjsj
     *
     * @mbggenerated
     */
    public Date getdCjsj() {
        return dCjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_green_nl_txjl.d_cjsj
     *
     * @param dCjsj the value for t_green_nl_txjl.d_cjsj
     *
     * @mbggenerated
     */
    public void setdCjsj(Date dCjsj) {
        this.dCjsj = dCjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_green_nl_txjl.c_xguser
     *
     * @return the value of t_green_nl_txjl.c_xguser
     *
     * @mbggenerated
     */
    public String getcXguser() {
        return cXguser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_green_nl_txjl.c_xguser
     *
     * @param cXguser the value for t_green_nl_txjl.c_xguser
     *
     * @mbggenerated
     */
    public void setcXguser(String cXguser) {
        this.cXguser = cXguser == null ? null : cXguser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_green_nl_txjl.d_xgsj
     *
     * @return the value of t_green_nl_txjl.d_xgsj
     *
     * @mbggenerated
     */
    public Date getdXgsj() {
        return dXgsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_green_nl_txjl.d_xgsj
     *
     * @param dXgsj the value for t_green_nl_txjl.d_xgsj
     *
     * @mbggenerated
     */
    public void setdXgsj(Date dXgsj) {
        this.dXgsj = dXgsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_nl_txjl
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", cLsh=").append(cLsh);
        sb.append(", cDzzh=").append(cDzzh);
        sb.append(", cFkzh=").append(cFkzh);
        sb.append(", nTxje=").append(nTxje);
        sb.append(", nTxnl=").append(nTxnl);
        sb.append(", dTxsj=").append(dTxsj);
        sb.append(", dDzsj=").append(dDzsj);
        sb.append(", cSfcg=").append(cSfcg);
        sb.append(", cTxfs=").append(cTxfs);
        sb.append(", cTxyh=").append(cTxyh);
        sb.append(", cTxkh=").append(cTxkh);
        sb.append(", cZzdh=").append(cZzdh);
        sb.append(", cBz=").append(cBz);
        sb.append(", cZt=").append(cZt);
        sb.append(", cCjuser=").append(cCjuser);
        sb.append(", dCjsj=").append(dCjsj);
        sb.append(", cXguser=").append(cXguser);
        sb.append(", dXgsj=").append(dXgsj);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}