package com.plate.publicmag.model;

import java.io.Serializable;
import java.util.Date;

public class PublicUser implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_user.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_user.username
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_user.loginname
     *
     * @mbggenerated
     */
    private String loginname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_user.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_user.user_type
     *
     * @mbggenerated
     */
    private String userType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_user.idcard_type
     *
     * @mbggenerated
     */
    private String idcardType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_user.idcard
     *
     * @mbggenerated
     */
    private String idcard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_user.address_area
     *
     * @mbggenerated
     */
    private String addressArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_user.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_user.address_domicile_area
     *
     * @mbggenerated
     */
    private String addressDomicileArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_user.address_domicile
     *
     * @mbggenerated
     */
    private String addressDomicile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_user.mobilephone
     *
     * @mbggenerated
     */
    private String mobilephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_user.telephone
     *
     * @mbggenerated
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_user.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_user.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_user.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_user.create_userid
     *
     * @mbggenerated
     */
    private Integer createUserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_user.create_username
     *
     * @mbggenerated
     */
    private String createUsername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_user.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_user.update_userid
     *
     * @mbggenerated
     */
    private Integer updateUserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_user.update_username
     *
     * @mbggenerated
     */
    private Date updateUsername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public_user
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public_user.id
     *
     * @return the value of public_user.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public_user.id
     *
     * @param id the value for public_user.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public_user.username
     *
     * @return the value of public_user.username
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public_user.username
     *
     * @param username the value for public_user.username
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public_user.loginname
     *
     * @return the value of public_user.loginname
     *
     * @mbggenerated
     */
    public String getLoginname() {
        return loginname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public_user.loginname
     *
     * @param loginname the value for public_user.loginname
     *
     * @mbggenerated
     */
    public void setLoginname(String loginname) {
        this.loginname = loginname == null ? null : loginname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public_user.password
     *
     * @return the value of public_user.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public_user.password
     *
     * @param password the value for public_user.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public_user.user_type
     *
     * @return the value of public_user.user_type
     *
     * @mbggenerated
     */
    public String getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public_user.user_type
     *
     * @param userType the value for public_user.user_type
     *
     * @mbggenerated
     */
    public void setUserType(String userType) {
        this.userType = userType == null ? null : userType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public_user.idcard_type
     *
     * @return the value of public_user.idcard_type
     *
     * @mbggenerated
     */
    public String getIdcardType() {
        return idcardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public_user.idcard_type
     *
     * @param idcardType the value for public_user.idcard_type
     *
     * @mbggenerated
     */
    public void setIdcardType(String idcardType) {
        this.idcardType = idcardType == null ? null : idcardType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public_user.idcard
     *
     * @return the value of public_user.idcard
     *
     * @mbggenerated
     */
    public String getIdcard() {
        return idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public_user.idcard
     *
     * @param idcard the value for public_user.idcard
     *
     * @mbggenerated
     */
    public void setIdcard(String idcard) {
        this.idcard = idcard == null ? null : idcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public_user.address_area
     *
     * @return the value of public_user.address_area
     *
     * @mbggenerated
     */
    public String getAddressArea() {
        return addressArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public_user.address_area
     *
     * @param addressArea the value for public_user.address_area
     *
     * @mbggenerated
     */
    public void setAddressArea(String addressArea) {
        this.addressArea = addressArea == null ? null : addressArea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public_user.address
     *
     * @return the value of public_user.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public_user.address
     *
     * @param address the value for public_user.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public_user.address_domicile_area
     *
     * @return the value of public_user.address_domicile_area
     *
     * @mbggenerated
     */
    public String getAddressDomicileArea() {
        return addressDomicileArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public_user.address_domicile_area
     *
     * @param addressDomicileArea the value for public_user.address_domicile_area
     *
     * @mbggenerated
     */
    public void setAddressDomicileArea(String addressDomicileArea) {
        this.addressDomicileArea = addressDomicileArea == null ? null : addressDomicileArea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public_user.address_domicile
     *
     * @return the value of public_user.address_domicile
     *
     * @mbggenerated
     */
    public String getAddressDomicile() {
        return addressDomicile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public_user.address_domicile
     *
     * @param addressDomicile the value for public_user.address_domicile
     *
     * @mbggenerated
     */
    public void setAddressDomicile(String addressDomicile) {
        this.addressDomicile = addressDomicile == null ? null : addressDomicile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public_user.mobilephone
     *
     * @return the value of public_user.mobilephone
     *
     * @mbggenerated
     */
    public String getMobilephone() {
        return mobilephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public_user.mobilephone
     *
     * @param mobilephone the value for public_user.mobilephone
     *
     * @mbggenerated
     */
    public void setMobilephone(String mobilephone) {
        this.mobilephone = mobilephone == null ? null : mobilephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public_user.telephone
     *
     * @return the value of public_user.telephone
     *
     * @mbggenerated
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public_user.telephone
     *
     * @param telephone the value for public_user.telephone
     *
     * @mbggenerated
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public_user.remark
     *
     * @return the value of public_user.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public_user.remark
     *
     * @param remark the value for public_user.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public_user.status
     *
     * @return the value of public_user.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public_user.status
     *
     * @param status the value for public_user.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public_user.create_time
     *
     * @return the value of public_user.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public_user.create_time
     *
     * @param createTime the value for public_user.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public_user.create_userid
     *
     * @return the value of public_user.create_userid
     *
     * @mbggenerated
     */
    public Integer getCreateUserid() {
        return createUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public_user.create_userid
     *
     * @param createUserid the value for public_user.create_userid
     *
     * @mbggenerated
     */
    public void setCreateUserid(Integer createUserid) {
        this.createUserid = createUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public_user.create_username
     *
     * @return the value of public_user.create_username
     *
     * @mbggenerated
     */
    public String getCreateUsername() {
        return createUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public_user.create_username
     *
     * @param createUsername the value for public_user.create_username
     *
     * @mbggenerated
     */
    public void setCreateUsername(String createUsername) {
        this.createUsername = createUsername == null ? null : createUsername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public_user.update_time
     *
     * @return the value of public_user.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public_user.update_time
     *
     * @param updateTime the value for public_user.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public_user.update_userid
     *
     * @return the value of public_user.update_userid
     *
     * @mbggenerated
     */
    public Integer getUpdateUserid() {
        return updateUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public_user.update_userid
     *
     * @param updateUserid the value for public_user.update_userid
     *
     * @mbggenerated
     */
    public void setUpdateUserid(Integer updateUserid) {
        this.updateUserid = updateUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public_user.update_username
     *
     * @return the value of public_user.update_username
     *
     * @mbggenerated
     */
    public Date getUpdateUsername() {
        return updateUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public_user.update_username
     *
     * @param updateUsername the value for public_user.update_username
     *
     * @mbggenerated
     */
    public void setUpdateUsername(Date updateUsername) {
        this.updateUsername = updateUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_user
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", username=").append(username);
        sb.append(", loginname=").append(loginname);
        sb.append(", password=").append(password);
        sb.append(", userType=").append(userType);
        sb.append(", idcardType=").append(idcardType);
        sb.append(", idcard=").append(idcard);
        sb.append(", addressArea=").append(addressArea);
        sb.append(", address=").append(address);
        sb.append(", addressDomicileArea=").append(addressDomicileArea);
        sb.append(", addressDomicile=").append(addressDomicile);
        sb.append(", mobilephone=").append(mobilephone);
        sb.append(", telephone=").append(telephone);
        sb.append(", remark=").append(remark);
        sb.append(", status=").append(status);
        sb.append(", createTime=").append(createTime);
        sb.append(", createUserid=").append(createUserid);
        sb.append(", createUsername=").append(createUsername);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", updateUserid=").append(updateUserid);
        sb.append(", updateUsername=").append(updateUsername);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}