package com.greenplatform.dao;

import com.greenplatform.model.PlateUserRole;
import com.greenplatform.model.PlateUserRoleExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface PlateUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plate_user_role
     *
     * @mbggenerated
     */
    int countByExample(PlateUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plate_user_role
     *
     * @mbggenerated
     */
    int deleteByExample(PlateUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plate_user_role
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String nRole);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plate_user_role
     *
     * @mbggenerated
     */
    int insert(PlateUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plate_user_role
     *
     * @mbggenerated
     */
    int insertSelective(PlateUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plate_user_role
     *
     * @mbggenerated
     */
    List<PlateUserRole> selectByExample(PlateUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plate_user_role
     *
     * @mbggenerated
     */
    PlateUserRole selectByPrimaryKey(String nRole);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plate_user_role
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PlateUserRole record, @Param("example") PlateUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plate_user_role
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") PlateUserRole record, @Param("example") PlateUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plate_user_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PlateUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plate_user_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PlateUserRole record);
}