package com.greenplatform.dao;

import com.greenplatform.model.PlateUserBlacklist;
import com.greenplatform.model.PlateUserBlacklistExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PlateUserBlacklistMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plate_user_blacklist
     *
     * @mbggenerated
     */
    int countByExample(PlateUserBlacklistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plate_user_blacklist
     *
     * @mbggenerated
     */
    int deleteByExample(PlateUserBlacklistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plate_user_blacklist
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String cLsh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plate_user_blacklist
     *
     * @mbggenerated
     */
    int insert(PlateUserBlacklist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plate_user_blacklist
     *
     * @mbggenerated
     */
    int insertSelective(PlateUserBlacklist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plate_user_blacklist
     *
     * @mbggenerated
     */
    List<PlateUserBlacklist> selectByExample(PlateUserBlacklistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plate_user_blacklist
     *
     * @mbggenerated
     */
    PlateUserBlacklist selectByPrimaryKey(String cLsh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plate_user_blacklist
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PlateUserBlacklist record, @Param("example") PlateUserBlacklistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plate_user_blacklist
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") PlateUserBlacklist record, @Param("example") PlateUserBlacklistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plate_user_blacklist
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PlateUserBlacklist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plate_user_blacklist
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PlateUserBlacklist record);
}