package com.greenplatform.dao;

import com.greenplatform.model.PlateCodeDmlb;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface PlateCodeDmlbMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plate_code_dmlb
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String cDmlb);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plate_code_dmlb
     *
     * @mbggenerated
     */
    int insert(PlateCodeDmlb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plate_code_dmlb
     *
     * @mbggenerated
     */
    PlateCodeDmlb selectByPrimaryKey(String cDmlb);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plate_code_dmlb
     *
     * @mbggenerated
     */
    List<PlateCodeDmlb> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plate_code_dmlb
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PlateCodeDmlb record);


    List selectPlateCodeDmlb (PlateCodeDmlb plateCodeDmlb);//查询代码类别
}