package com.greenplatform.dao;

import com.greenplatform.model.PlateUserYwqx;
import com.greenplatform.model.PlateUserYwqxExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface PlateUserYwqxMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plate_user_ywqx
     *
     * @mbggenerated
     */
    int countByExample(PlateUserYwqxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plate_user_ywqx
     *
     * @mbggenerated
     */
    int deleteByExample(PlateUserYwqxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plate_user_ywqx
     *
     * @mbggenerated
     */
    int insert(PlateUserYwqx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plate_user_ywqx
     *
     * @mbggenerated
     */
    int insertSelective(PlateUserYwqx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plate_user_ywqx
     *
     * @mbggenerated
     */
    List<PlateUserYwqx> selectByExample(PlateUserYwqxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plate_user_ywqx
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PlateUserYwqx record, @Param("example") PlateUserYwqxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plate_user_ywqx
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") PlateUserYwqx record, @Param("example") PlateUserYwqxExample example);
}