package com.greenplatform.dao;

import com.greenplatform.model.TGreenNlZjnlmx;
import com.greenplatform.model.TGreenNlZjnlmxExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface TGreenNlZjnlmxMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_nl_zjnlmx
     *
     * @mbggenerated
     */
    int countByExample(TGreenNlZjnlmxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_nl_zjnlmx
     *
     * @mbggenerated
     */
    int deleteByExample(TGreenNlZjnlmxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_nl_zjnlmx
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String cLsh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_nl_zjnlmx
     *
     * @mbggenerated
     */
    int insert(TGreenNlZjnlmx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_nl_zjnlmx
     *
     * @mbggenerated
     */
    int insertSelective(TGreenNlZjnlmx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_nl_zjnlmx
     *
     * @mbggenerated
     */
    List<TGreenNlZjnlmx> selectByExample(TGreenNlZjnlmxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_nl_zjnlmx
     *
     * @mbggenerated
     */
    TGreenNlZjnlmx selectByPrimaryKey(String cLsh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_nl_zjnlmx
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TGreenNlZjnlmx record, @Param("example") TGreenNlZjnlmxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_nl_zjnlmx
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TGreenNlZjnlmx record, @Param("example") TGreenNlZjnlmxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_nl_zjnlmx
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TGreenNlZjnlmx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_nl_zjnlmx
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TGreenNlZjnlmx record);
}