package com.greenplatform.dao;

import com.greenplatform.model.TGreenNlCzjl;
import com.greenplatform.model.TGreenNlCzjlExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface TGreenNlCzjlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_nl_czjl
     *
     * @mbggenerated
     */
    int countByExample(TGreenNlCzjlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_nl_czjl
     *
     * @mbggenerated
     */
    int deleteByExample(TGreenNlCzjlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_nl_czjl
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String cLsh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_nl_czjl
     *
     * @mbggenerated
     */
    int insert(TGreenNlCzjl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_nl_czjl
     *
     * @mbggenerated
     */
    int insertSelective(TGreenNlCzjl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_nl_czjl
     *
     * @mbggenerated
     */
    List<TGreenNlCzjl> selectByExample(TGreenNlCzjlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_nl_czjl
     *
     * @mbggenerated
     */
    TGreenNlCzjl selectByPrimaryKey(String cLsh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_nl_czjl
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TGreenNlCzjl record, @Param("example") TGreenNlCzjlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_nl_czjl
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TGreenNlCzjl record, @Param("example") TGreenNlCzjlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_nl_czjl
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TGreenNlCzjl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_nl_czjl
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TGreenNlCzjl record);
}