package com.greenplatform.dao;

import com.greenplatform.model.TGreenNlTxjl;
import com.greenplatform.model.TGreenNlTxjlExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface TGreenNlTxjlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_nl_txjl
     *
     * @mbggenerated
     */
    int countByExample(TGreenNlTxjlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_nl_txjl
     *
     * @mbggenerated
     */
    int deleteByExample(TGreenNlTxjlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_nl_txjl
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String cLsh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_nl_txjl
     *
     * @mbggenerated
     */
    int insert(TGreenNlTxjl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_nl_txjl
     *
     * @mbggenerated
     */
    int insertSelective(TGreenNlTxjl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_nl_txjl
     *
     * @mbggenerated
     */
    List<TGreenNlTxjl> selectByExample(TGreenNlTxjlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_nl_txjl
     *
     * @mbggenerated
     */
    TGreenNlTxjl selectByPrimaryKey(String cLsh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_nl_txjl
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TGreenNlTxjl record, @Param("example") TGreenNlTxjlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_nl_txjl
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TGreenNlTxjl record, @Param("example") TGreenNlTxjlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_nl_txjl
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TGreenNlTxjl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_nl_txjl
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TGreenNlTxjl record);
}