package com.greenplatform.dao;

import com.greenplatform.model.TGreenZzZjzzmx;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface TGreenZzZjzzmxMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_zz_zjzzmx
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String cLsh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_zz_zjzzmx
     *
     * @mbggenerated
     */
    int insert(TGreenZzZjzzmx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_zz_zjzzmx
     *
     * @mbggenerated
     */
    TGreenZzZjzzmx selectByPrimaryKey(String cLsh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_zz_zjzzmx
     *
     * @mbggenerated
     */
    List<TGreenZzZjzzmx> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_zz_zjzzmx
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TGreenZzZjzzmx record);


    List selectTGreenZzZjzzmx (TGreenZzZjzzmx tGreenZzZjzzmx);//查询增加种子明细
}