package com.greenplatform.dao;

import com.greenplatform.model.TGreenZzJzjl;
import com.greenplatform.model.TGreenZzJzjlExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface TGreenZzJzjlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_zz_jzjl
     *
     * @mbggenerated
     */
    int countByExample(TGreenZzJzjlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_zz_jzjl
     *
     * @mbggenerated
     */
    int deleteByExample(TGreenZzJzjlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_zz_jzjl
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(@Param("cLsh") String cLsh, @Param("cZzzjlsh") String cZzzjlsh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_zz_jzjl
     *
     * @mbggenerated
     */
    int insert(TGreenZzJzjl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_zz_jzjl
     *
     * @mbggenerated
     */
    int insertSelective(TGreenZzJzjl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_zz_jzjl
     *
     * @mbggenerated
     */
    List<TGreenZzJzjl> selectByExample(TGreenZzJzjlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_zz_jzjl
     *
     * @mbggenerated
     */
    TGreenZzJzjl selectByPrimaryKey(@Param("cLsh") String cLsh, @Param("cZzzjlsh") String cZzzjlsh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_zz_jzjl
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TGreenZzJzjl record, @Param("example") TGreenZzJzjlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_zz_jzjl
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TGreenZzJzjl record, @Param("example") TGreenZzJzjlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_zz_jzjl
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TGreenZzJzjl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_zz_jzjl
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TGreenZzJzjl record);
}