package com.greenplatform.dao;

import com.greenplatform.model.TGreenNlJsnlmx;
import com.greenplatform.model.TGreenNlJsnlmxExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface TGreenNlJsnlmxMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_nl_jsnlmx
     *
     * @mbggenerated
     */
    int countByExample(TGreenNlJsnlmxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_nl_jsnlmx
     *
     * @mbggenerated
     */
    int deleteByExample(TGreenNlJsnlmxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_nl_jsnlmx
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String cLsh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_nl_jsnlmx
     *
     * @mbggenerated
     */
    int insert(TGreenNlJsnlmx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_nl_jsnlmx
     *
     * @mbggenerated
     */
    int insertSelective(TGreenNlJsnlmx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_nl_jsnlmx
     *
     * @mbggenerated
     */
    List<TGreenNlJsnlmx> selectByExample(TGreenNlJsnlmxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_nl_jsnlmx
     *
     * @mbggenerated
     */
    TGreenNlJsnlmx selectByPrimaryKey(String cLsh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_nl_jsnlmx
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TGreenNlJsnlmx record, @Param("example") TGreenNlJsnlmxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_nl_jsnlmx
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TGreenNlJsnlmx record, @Param("example") TGreenNlJsnlmxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_nl_jsnlmx
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TGreenNlJsnlmx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_nl_jsnlmx
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TGreenNlJsnlmx record);
}