package com.greenplatform.dao;

import com.greenplatform.model.TGreenRwRwmx;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface TGreenRwRwmxMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_rw_rwmx
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(@Param("cUserid") String cUserid, @Param("cRwlb") String cRwlb, @Param("cRwday") String cRwday);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_rw_rwmx
     *
     * @mbggenerated
     */
    int insert(TGreenRwRwmx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_rw_rwmx
     *
     * @mbggenerated
     */
    TGreenRwRwmx selectByPrimaryKey(@Param("cUserid") String cUserid, @Param("cRwlb") String cRwlb, @Param("cRwday") String cRwday);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_rw_rwmx
     *
     * @mbggenerated
     */
    List<TGreenRwRwmx> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_rw_rwmx
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TGreenRwRwmx record);

    List selectTGreenRwRwmx (TGreenRwRwmx tGreenRwRwmx);//查询任务完成量
}