package com.greenplatform.dao;

import com.greenplatform.model.TGreenNlHz;
import com.greenplatform.model.TGreenNlHzExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface TGreenNlHzMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_nl_hz
     *
     * @mbggenerated
     */
    int countByExample(TGreenNlHzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_nl_hz
     *
     * @mbggenerated
     */
    int deleteByExample(TGreenNlHzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_nl_hz
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String cUserid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_nl_hz
     *
     * @mbggenerated
     */
    int insert(TGreenNlHz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_nl_hz
     *
     * @mbggenerated
     */
    int insertSelective(TGreenNlHz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_nl_hz
     *
     * @mbggenerated
     */
    List<TGreenNlHz> selectByExample(TGreenNlHzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_nl_hz
     *
     * @mbggenerated
     */
    TGreenNlHz selectByPrimaryKey(String cUserid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_nl_hz
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TGreenNlHz record, @Param("example") TGreenNlHzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_nl_hz
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TGreenNlHz record, @Param("example") TGreenNlHzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_nl_hz
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TGreenNlHz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_nl_hz
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TGreenNlHz record);
}