package com.greenplatform.dao;

import com.greenplatform.model.TGreenNlHz;
import java.util.List;

public interface TGreenNlHzMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_nl_hz
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String cUserid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_nl_hz
     *
     * @mbggenerated
     */
    int insert(TGreenNlHz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_nl_hz
     *
     * @mbggenerated
     */
    TGreenNlHz selectByPrimaryKey(String cUserid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_nl_hz
     *
     * @mbggenerated
     */
    List<TGreenNlHz> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_nl_hz
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TGreenNlHz record);
}