package com.greenplatform.dao;

import com.greenplatform.model.TGreenZzZjzzmx;
import com.greenplatform.model.TGreenZzZjzzmxExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface TGreenZzZjzzmxMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_zz_zjzzmx
     *
     * @mbggenerated
     */
    int countByExample(TGreenZzZjzzmxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_zz_zjzzmx
     *
     * @mbggenerated
     */
    int deleteByExample(TGreenZzZjzzmxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_zz_zjzzmx
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String cLsh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_zz_zjzzmx
     *
     * @mbggenerated
     */
    int insert(TGreenZzZjzzmx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_zz_zjzzmx
     *
     * @mbggenerated
     */
    int insertSelective(TGreenZzZjzzmx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_zz_zjzzmx
     *
     * @mbggenerated
     */
    List<TGreenZzZjzzmx> selectByExample(TGreenZzZjzzmxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_zz_zjzzmx
     *
     * @mbggenerated
     */
    TGreenZzZjzzmx selectByPrimaryKey(String cLsh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_zz_zjzzmx
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TGreenZzZjzzmx record, @Param("example") TGreenZzZjzzmxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_zz_zjzzmx
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TGreenZzZjzzmx record, @Param("example") TGreenZzZjzzmxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_zz_zjzzmx
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TGreenZzZjzzmx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_zz_zjzzmx
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TGreenZzZjzzmx record);
}