package com.greenplatform.dao;

import com.greenplatform.model.TGreenSpSpmx;
import com.greenplatform.model.TGreenSpSpmxExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface TGreenSpSpmxMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_sp_spmx
     *
     * @mbggenerated
     */
    int countByExample(TGreenSpSpmxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_sp_spmx
     *
     * @mbggenerated
     */
    int deleteByExample(TGreenSpSpmxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_sp_spmx
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String cSpbh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_sp_spmx
     *
     * @mbggenerated
     */
    int insert(TGreenSpSpmx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_sp_spmx
     *
     * @mbggenerated
     */
    int insertSelective(TGreenSpSpmx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_sp_spmx
     *
     * @mbggenerated
     */
    List<TGreenSpSpmx> selectByExample(TGreenSpSpmxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_sp_spmx
     *
     * @mbggenerated
     */
    TGreenSpSpmx selectByPrimaryKey(String cSpbh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_sp_spmx
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TGreenSpSpmx record, @Param("example") TGreenSpSpmxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_sp_spmx
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TGreenSpSpmx record, @Param("example") TGreenSpSpmxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_sp_spmx
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TGreenSpSpmx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_green_sp_spmx
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TGreenSpSpmx record);
}